### ISSUE TITLE
Check when unnecessarily suppressed

### ISSUE THREAD

**Issue by ben-manes** [uber/NullAway#100]
As project code evolves and as this checker's false positives are squashed, some suppressions will no longer be needed. That could then lead to new scenarios going uncaught because a stale suppression remains, but a new NPE is introduced. For code health, it would be good to be optionally stricter about suppressions.

**Comment by msridhar** [comment]
Interesting.  But I think this might be a feature request for Error Prone itself.  If you look at [their code](https://github.com/google/error-prone/blob/master/check_api/src/main/java/com/google/errorprone/scanner/ErrorProneScanner.java#L489) the core `ErrorProneScanner` doesn't even call into a checker if warnings have been suppressed.  But in general I think it'd be cool if Error Prone supported a mode for finding unnecessary suppressions; this could be completely independent of what checkers are being used I think.

Maybe you could file an issue with Error Prone on this one?

**Comment by ben-manes** [comment]
Thanks, done.
