### ISSUE TITLE
JSpecify: Use `@NullMarked` instead of `-XepOpt:NullAway:AnnotatedPackages`

### ISSUE THREAD

**Issue by pemistahl** [uber/NullAway#1042]
While testing the JSpecify annotations with NullAway, I thought I would be able to remove the `-XepOpt:NullAway:AnnotatedPackages` setting in favor of using the `@NullMarked` annotation. I want to specify the code to be checked on class level instead of package level. This does not seem to be possible right now. Setting the `@NullMarked` annotation does not have any effect. However, when I remove the `AnnotatedPackages` setting NullAway even fails to initialize at all.

Will this be fixed in a future release to provide conformity with the JSpecify specification?

**Comment by beatbrot** [comment]
Just a sidenote: I think both variants should work at the same time.
In my codebase, it is not feasable to add NullMarked everywhere, therefore I enjoyed using `NullAway:AnnotatedPackages`. I want to keep doing this :)

**Comment by msridhar** [comment]
Thanks for the feedback!  We have an open issue on this, #574.  Let's continue the discussion there.

**Comment by msridhar** [comment]
Duplicate of #574
