### ISSUE TITLE
null-away fails when returning a choice between two nullables

### ISSUE THREAD

**Issue by moaxcp** [uber/NullAway#1058]
I have been running into an issue in methods that make a choice between two nullables. The method never returns null but null-away fails. I made an example [here](https://github.com/moaxcp/nullaway-example/blob/master/example-project/src/main/java/com/github/moaxcp/nullaway/project/Choice.java#L8).

```
    public static Integer choiceOrZero(@Nullable Integer left, @Nullable Integer right) {
        if (right == null && left == null) {
            return 0;
        }
        if (right == null) {
            return left;
        }
        if (left == null) {
            return right;
        }
        return right;
    }
```

Here is the error

```
/projects/nullaway-example/example-project/src/main/java/com/github/moaxcp/nullaway/project/Choice.java:13: error: [NullAway] returning @Nullable expression from method with @NonNull return type
            return left;
            ^
    (see http://t.uber.com/nullaway )
```

I think null-away is somehow missing that the first check ensures both left and right are not null.

The solution is to do something like this:

```
    public static Integer choiceOrZeroFixed(@Nullable Integer left, @Nullable Integer right) {
        if (right == null && left == null) {
            return 0;
        }
        if (right == null) {
            return requireNonNull(left);
        }
        if (left == null) {
            return requireNonNull(right);
        }
        return right;
    }
```

**Comment by msridhar** [comment]
Hi @moaxcp thanks for the report.  You're right that NullAway doesn't support your code as written.  To avoid warnings, we would have to track information like `right != null || left != null` after the first `if` condition.  Tracking these disjunctive conditions can become expensive, so NullAway avoids it for efficient checking.

Your solution is one way to work around the problem.  Alternately you could write the code like this:
```java
    public static Integer choiceOrZeroFixed(@Nullable Integer left, @Nullable Integer right) {
        if (right == null) {
            return left == null ? 0 : left;
        } else {
            return right;
        }
    }
```
I _think_ this logic is equivalent to what you wrote, and NullAway can prove it safe.  But you might this version to be harded to understand.  And there are probably other cases that cannot be re-written as easily.

I'm going to close as I don't think we have plans to support the original case, but please feel free to report other issues to us!
