### ISSUE TITLE
False Positive when using JSpecify Nullable on varargs elements

### ISSUE THREAD

**Issue by lukasgraef** [uber/NullAway#1088]
When using Nullaway 0.12.1 in default mode in combination with JSpecify Nullable on vararg elements, like
` public static void foo(@org.jspecify.annotations.Nullable String... args)`, I get the following error when passing a nullable parameter:
`[NullAway] passing @Nullable parameter (String) null where @NonNull is required`, although Nullable elements are explicitly permitted.

If the function is defined in the same class or even the same module of the caller, this works without any error.

The issue only arises when the function is defined outside the caller's module. I suspect this has to do with the differences between the source and bytecode analysis that Nullaway does.

I could reproduce this within the VarargsTests, when creating a testcase with varargs from bytecode: https://github.com/uber/NullAway/compare/master...lukasgraef:NullAway:master

**Comment by N1k145** [comment]
I have the same issue even when using classic "javax.annotation" Nullable. And those I can't place like the JSpecify anotations.
Even when both methods are part of the same class (but there is an interface involved, no idea it this creates the same scenario ans in @lukasgraef example)

**Comment by msridhar** [comment]
I'll try to look at this soon. @N1k145 for your case an example would be helpful

**Comment by N1k145** [comment]
@msridhar https://github.com/N1k145/NullAway/tree/issue1088

**Comment by msridhar** [comment]
@N1k145 for clarity I've split out your issue into #1090.  Let's discuss there.  #1089 should fix the original issue reported here.

**Comment by msridhar** [comment]
NullAway 0.12.2 is released with the fix for this issue.  FYI @sdeleuze
