### ISSUE TITLE
Another varargs `@Nullable` issue

### ISSUE THREAD

**Issue by msridhar** [uber/NullAway#1090]
I have the same issue even when using classic "javax.annotation" Nullable. And those I can't place like the JSpecify anotations.
Even when both methods are part of the same class (but there is an interface involved, no idea it this creates the same scenario ans in @lukasgraef example)

_Originally posted by @N1k145 in https://github.com/uber/NullAway/issues/1088#issuecomment-2535859059_

And: 

> @msridhar https://github.com/N1k145/NullAway/tree/issue1088

**Comment by msridhar** [comment]
@N1k145 I tried out your test case.  The first thing I see is that the edited `Varargs` class does not compile:

```
NullAway/test-java-lib/src/main/java/com/uber/lib/Varargs.java:17: error: [NullAway] passing @Nullable parameter 'test' where @NonNull is required
    new Varargs().typeUseNullableElements(val, test);
```

This is due to changes made in NullAway 0.12.0 to better support JSpecify annotations.  By default, if you want to be able to pass a `@Nullable` array in the varargs position, you must annotate the varargs parameter with a _type use_ `@Nullable` annotation, like JSpecify's `@Nullable`.  If you write `foo(@Nullable String... args)` and `Nullable` is a _declaration_ annotation (like `javax.annotation.Nullable`), NullAway treats that as applying to individual varargs parameters (the more common case), not the varargs array itself.  Previously, NullAway behaved differently than this, and if you'd like to re-enable the old behavior, you can temporarily pass the option `-XepOpt:NullAway:LegacyAnnotationLocations`.  But, this option will go away eventually, so my suggestion is to just use the JSpecify `@Nullable` annotation whenever you want to be able to pass a `@Nullable` varargs array.  See [our wiki page](https://github.com/uber/NullAway/wiki/JSpecify-Support) for more details, and [here](https://github.com/uber/NullAway/pull/1025) for all the details on how NullAway interprets varargs parameter annotations in different modes.

Does the above answer your question?

**Comment by N1k145** [comment]
@msridhar Thank you for the explanation, we did directly the bump to 0.12.1 so we did not use 0.12.0 directly and did not notice the change there.

So you are saying for this usecase there is now (or actually in the future) a hard dependency on JSpecify?

**Comment by msridhar** [comment]
> So you are saying for this usecase there is now (or actually in the future) a hard dependency on JSpecify?

No, any annotation named `@Nullable` that is a type use annotation should work.  So, the Checker Framework `@Nullable` should work (or you could define your own).  If you have a strong reason not to use JSpecify, though, we'd be interested to know about it.

**Comment by N1k145** [comment]
No we have nothing against JSpecify but we have not yet looked into it. I read up on it today and we are probably migration over to it in the next weeks, so this can be closed.

**Comment by msridhar** [comment]
Ok! Note that temporarily you can use the JSpecify `@Nullable` in this one place while retaining extant annotations elsewhere, if that will unblock you.
