### ISSUE TITLE
Field in unannotated code should be considered non-null only for field reads

### ISSUE THREAD

**Issue by agrieve** [uber/NullAway#1101]
(Sorry if this is filed somewhere already) 

It's come up a couple times now where we have generated code that creates struct-like classes with public fields. The NullAway default for unannotated code is to treat public fields as non-null, which removes warnings for field reads, but not for field writes. It would be great if fields of of unannotated classes would be considered `@Nullable` in the context of field writes.

In the particular case I'm working, I can update our code generator to annotate the fields, but thought I'd file this anyways.

**Comment by msridhar** [comment]
This is not expected. How is the code designated as unannotated? Is it generated into a different package?

**Comment by agrieve** [comment]
I'm setting `-XepOpt:NullAway:AnnotatedPackages=` such that no classes are considered annotated unless they are marked with `@NullMarked`.

**Comment by msridhar** [comment]
Thanks for the report; a PR fix is up now.  This bug has existed in NullAway for years!

**Comment by msridhar** [comment]
@agrieve would it be helpful to you to have a release with this fix?

**Comment by agrieve** [comment]
Thanks for such a quick fix! I've fixed our main code generator that emitted these fields, so I don't think there'd be many other instances, so I wouldn't cut a release just for this if there's some overhead in doing so.

**Comment by msridhar** [comment]
Ok, sounds good.  I might wait then until we can get a couple more fixes in.
