### ISSUE TITLE
Maven annotationProcessorPaths (APT) required for NullAway intereres with other existing APT processors on project classpath

### ISSUE THREAD

**Issue by vorburger** [uber/NullAway#118]
I'm exploring using NullAway (v0.3.2) in a (large) existing Maven-based project which is not going to switch from Maven to e.g. Gradle any time soon, and have set it up as documented on https://github.com/uber/NullAway/wiki/Configuration#maven.

Some modules of this large existig project use at least one existing APT based processor; I've hit the snag related to http://immutables.github.io. This APT processor is not registered via the `maven-compiler-plugin`'s `annotationProcessorPaths` but is a regular Maven `<dependency>` on some modules classpath; as recommended by Immutables documentation (also because their same JAR contains both an APT processor as well as annotations).  The problem is not related to Immutables.org per se and would occur with any other APT processor as well, if its a regular `<dependency>`.

Because [the maven-compiler-plugin, apparently](https://maven.apache.org/plugins//compile-mojo.html), for `annotationProcessorPaths` _"If specified, the compiler will detect annotation processors only in those classpath elements. If omitted, the default classpath is used to detect annotation processors."_, using NullAway deactivates an existing APT processor such as Immutables.org ... :-(

I can put together a simple standalone project to illustrate this problem, if it would help to clarify.

Some questions / points for discussion:

1. Does NullAway *have* to be on the `annotationProcessorPaths` of the `maven-compiler-plugin`? Couldn't it also at least optionally integrate with error-prone as a dependency of `maven-compiler-plugin`, just like `error_prone_core` itself?

2. Would you consider this "interference" of an APT processor on maven-compiler-plugin's `annotationProcessorPaths` with one it detects on the regular dependencies consider a `maven-compiler-plugin` problem? Then all hope is lost... :smile: 

One possible workaround I've found is that if I put Immutables.org on the `annotationProcessorPaths` in addition (!) to being on the project's `dependencies` then it works. The trouble with that is I'm not sure that is feasible at scale - doing this would mean that hundreds of Maven modules suddenly have that particular APT processor activated, whereas before it was a dependency of only a handful of them... not sure about the build performance overhead this causes and would love to find a better solution - if anyone has any ideas?

**Comment by vorburger** [comment]
BTW: Working around "the other way", and having nullaway as a regular `dependency` instead of an `annotationProcessorPaths` doesn't work, but that's probably because error_prone_core is on the classsloader of the maven-compiler-plugin so it cannot the nullaway via ServiceLocator... but "polluting" (uncessearily) the project dependencies classpath with nullaway isn't great either anyway.

`com.google.errorprone.InvalidCommandLineOptionException: NullAway is not a valid checker name`

**Comment by kageiit** [comment]
@vorburger the proper fix would be to unwind immutables into tow artifacts. One for annotations and one for the compiler plugin. Many processors do it this way today like [Dagger](https://github.com/google/dagger), [Buttekrnife](https://github.com/JakeWharton/butterknife) etc.

[Autovalue](https://github.com/google/auto/issues/268) is moving to this format as well. This seems like an issue with the maven compiler plugin really. The proper way to go about it would be to make an upstream issue on immutables to also provide an option for separate artifacts one for annotations and one with the apt compiler plugin. They can continue to ship the artifact which bundles both together as well.

In the meanwhile, you could split up the artifact into two yourself for use in your codebase till the issue is fixed upstream.

**Comment by msridhar** [comment]
Thanks for the report @vorburger.  I think @kageiit has a good solution which will hopefully be workable.  Amazingly, just two days ago we were debugging an incompatibility between NullAway and Lombok when using Maven, and I now realize it's the same problem as this issue!

**Comment by vorburger** [comment]
Ok, I thanks for your feedback. I'll write up an issue proposing split Immutable.org JARs hopefully tomorrow, and then probably close this.

**Comment by vorburger** [comment]
==> https://github.com/immutables/immutables/issues/750
