### ISSUE TITLE
How to deal with nullability in  builders

### ISSUE THREAD

**Issue by bangarharshit** [uber/NullAway#121]
NullAway currently doesn't work with builders as the test below throws an error. The alternative is only to create Builder with required parameters in the constructor which may lead to a loss in readability.

If there are no alternatives, I will like to propose a solution to use some kind of required annotation with these fluent methods and another check can be written for that.
```java
import java.util.Optional;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public class Arbit {
  @Nonnull private final String requiredField;
  @Nullable private final String optionalField;

  private Arbit(Builder builder) {
    this.requiredField = builder.requiredField;
    this.optionalField = builder.optionalField;
  }

  public String getRequiredField() {
    return requiredField;
  }

  public Optional<String> getOptionalField() {
    return Optional.ofNullable(optionalField);
  }

  public static class Builder {
    @Nonnull private String requiredField;
    @Nullable private String optionalField;

    public Builder requiredField(@Nonnull String requiredField) {
      this.requiredField = requiredField;
      return this;
    }

    public Builder optionalField(@Nullable String optionalField) {
      this.optionalField = optionalField;
      return this;
    }

    public Builder fromPrototype(Arbit prototype) {
      requiredField = prototype.requiredField;
      optionalField = prototype.optionalField;
      return this;
    }

    public Arbit build() {
      return new Arbit(this);
    }
  }
}
```

Error
```
./gradlew assemble
Parallel execution is an incubating feature.
:compileJava
/Users/harshitbangar/test/src/main/java/com/Arbit.java:25: error: [NullAway] @NonNull field requiredField not initialized
    @Nonnull private String requiredField;
                            ^
    (see http://t.uber.com/nullaway )
1 error
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed with exit code 1; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED


Total time: 2.799 secs
```

**Comment by hzsweers** [comment]
Seems to me like a solution would be to either make required arguments part of the constructor or annotate the field with lazyinit?

**Comment by bangarharshit** [comment]
Thanks, lazyInit is a good idea. Agreed @NonNull is a lie. 

How do you guys think about another error-prone check for the builder that test all the required methods are invoked?  (not relevant to this so close this issue).

**Comment by msridhar** [comment]
If you assume the builder methods are invoked in a fluent manner, you could probably build a check that required methods are invoked in the chain of calls.  But if the usage isn't fluent, things will get trickier and could involve dataflow analysis and other expensive stuff.

**Comment by msridhar** [comment]
BTW, unless you're in a situation where you don't want to crash eagerly in production, I'd recommend `Objects.requireNonNull` over `@LazyInit`.  NullAway doesn't do any checking for `@LazyInit`, and for builders the initialization correctness is controlled by the client of the class, so that seems a bit unsafej.
