### ISSUE TITLE
Proposal: Annotation to denote that a utility nullchecks values

### ISSUE THREAD

**Issue by hzsweers** [uber/NullAway#126]
A common use case is a static util method like `TextUtils.isBlank()`, which, amongst other things, checks if it's null. It would be nice to annotate this with something like `@NullChecking` such that nullaway doesn't turn up false positives on these

**Comment by msridhar** [comment]
Yup, this is a duplicate of #96 I think.  Lemme know if you disagree

**Comment by hzsweers** [comment]
yep, I'll chime in there
