### ISSUE TITLE
better error message when an initializer sometimes writes a field

### ISSUE THREAD

**Issue by msridhar** [uber/NullAway#14]
Consider:
```java
Class Foo {
  Object f;
  @Initializer
  void init() {
    if (someCond()) {
      return;
    }
    f = new Object();
  }
}
```
For this code, we give an error message saying that `init()` does not initialize `f`, but it's a bit confusing since the method does write `f`.  Ideally, we'd give a clearer message indicating that `init()` does not initialize `f` on all control-flow paths.

**Comment by lazaroclapp** [comment]
Added a bit more info to the docs, here: https://github.com/uber/NullAway/wiki/Error-Messages

But probably still worth it to add the "along all control-flow paths" language to the error message itself. Will take on this if you are not already working on a fix.
