### ISSUE TITLE
Unable to get NullAway to work.

### ISSUE THREAD

**Issue by leinardi** [uber/NullAway#152]
I am trying to add NullAway to one of my open source projects on GitHub but I can't get it to work. I don't get any error or any kind of message, it just doesn't output anything.

Error-prone works fine, I tested it with and without NullAway.

The project is an Android library. You can find the all the information here:

- Commit that enables NullAway: https://github.com/leinardi/FloatingActionButtonSpeedDial/commit/18b77c3eb2f0edf76e055811edd98408ce26018a
- Test code  (the commented code is my test code for error-prone): https://github.com/leinardi/FloatingActionButtonSpeedDial/commit/e2b6dcc68669965e695007a4514f283a1d3394c9
- Build output: https://travis-ci.org/leinardi/FloatingActionButtonSpeedDial/builds/364822063?utm_source=github_status&utm_medium=notification

**Comment by lazaroclapp** [comment]
I believe at least an initial issue is that you are not setting up `-XepOpt:NullAway:AnnotatedPackages=` to check your code. You are passing it `com.uber`, so it will only check code under that package (assuming everything else is not correctly annotated). 

Perhaps you meant to do:

```
options.compilerArgs += 
  ["-Xep:NullAway:ERROR", 
   "-XepOpt:NullAway:AnnotatedPackages=com.leinardi"]
```

Or something even more specific, such as `com.leinardi.android.speeddial` just to test it is running for now.

See. https://github.com/uber/NullAway/wiki/Configuration for more details on configuring NullAway. Hopefully this solves the problem. Let us know either way.

**Comment by lazaroclapp** [comment]
No problem at all, glad it works now!
