### ISSUE TITLE
Feature request: Parsable output

### ISSUE THREAD

**Issue by tomasbjerre** [uber/NullAway#153]
Not sure if it is possible to implement here or if it is something that must be implemented in Google Error Prone. But there is not much happening there https://github.com/google/error-prone/issues/444.

I'm implementing a lib (https://github.com/tomasbjerre/violations-lib) that is used in a bunch of Gradle, Maven and Jenkins plugins. Would be nice to have a more robust support for NullAway.

**Comment by msridhar** [comment]
Hey, this is a good idea.  But I think the best solution is to get parsable output from Error Prone; NullAway directly uses Error Prone's reporting APIs.  I'm going to close this for now, but if there's a reason that generic Error Prone support wouldn't be good enough for NullAway we can reopen
