### ISSUE TITLE
Proposal: Assume `.equals()` allows Nullable parameters

### ISSUE THREAD

**Issue by hzsweers** [uber/NullAway#169]
I ran into this case when interop-ing from java to kotlin. For a Kotlin `data class`, it generates an `equals` implementation at compile-time. This `equals` method does _not_ have `@Nullable` on the input parameter.

<img width="877" alt="screen shot 2018-05-26 at 12 12 36 am" src="https://user-images.githubusercontent.com/1361086/40573760-e13c79f8-607a-11e8-8520-6010f40b72b2.png">

**Comment by hzsweers** [comment]
Made an issue to track in Kotlin as well - https://youtrack.jetbrains.net/issue/KT-24626

**Comment by msridhar** [comment]
This is a bit of a tricky one.  Probably the "right" thing to do is to treat `Object.equals()` as having a `@Nullable` parameter, in which case any override must also have a `@Nullable` parameter.  But this won't have the desired effect for this Kotlin example.  Best fix would be on the Kotlin side.  Please ping back if we really need a workaround on the NullAway side.

**Comment by hzsweers** [comment]
What about the proposal of checking for the metadata annotation and special casing kotlin data classes?

**Comment by msridhar** [comment]
The proposal is that whenever a class has a `@kotlin.Metadata` annotation, treat its `equals` method as having a `@Nullable` parameter?  If so, this sounds doable, but I'd still rather not do it unless the fix on the Kotlin side will take a while.  Any thoughts @hzsweers?

**Comment by hzsweers** [comment]
There's been an existing kotlin issue since January that hasn't been ack'd yet, so I don't know what its time table could be. I tried putting together a proposal PR, but I'm unable to get the kotlin project to index in my IDE :/

**Comment by hzsweers** [comment]
Nvm, maybe we can wait :) - https://github.com/JetBrains/kotlin/pull/1695

**Comment by hzsweers** [comment]
Wait is over, kotlin handles this properly for now
