### ISSUE TITLE
False Alarm - [NullAway] dereferenced expression <object> is @Nullable

### ISSUE THREAD

**Issue by mohammed-safiq** [uber/NullAway#171]
Hi, 

In ClassA, i have a method, 

public static boolean notEmpty(T obj)
{
        return obj != null;
}

In ClassB, i have a method, 

@Nullable
private T dummyObj;

public void foo()
{
           if(ClassA.notEmpty(dummyObj)
           {
              dummyObj.foo(); ----> line no 10
           }
}

Now eventhough i have notEmpty(...) check, it is throwing error like **dereferenced expression dummyObj is @Nullable** at line:10

But if i put normal null check like **dummyObj != null**, it is not throwing the error. 

What is wrong in the code?

Any help is highly appreciated.

**Comment by msridhar** [comment]
NullAway does not reason across procedure boundaries except via nullability annotations.  However, if you add the annotation `@Contract("null -> false")` to `notEmpty()` this should work; see [the docs](https://github.com/uber/NullAway/wiki/Supported-Annotations#contracts).

**Comment by msridhar** [comment]
If there's a further issue here please reopen

**Comment by mohammed-safiq** [comment]
@msridhar It is not working. Still the same error.

**Comment by msridhar** [comment]
Please provide a complete example (ideally a GitHub project) showing the
problem.
