### ISSUE TITLE
NPE in NullAway.safeInitByCalleeBefore()

### ISSUE THREAD

**Issue by joschi** [uber/NullAway#176]
### What version of Error Prone/NullAway are you using?

error-prone version: 2.3.1
nullaway version: 0.4.6
BugPattern: NullAway

### Does this issue reproduce with the latest release?

Yes.

### What did you do?

Trying to build dropwizard-hibernate with Error Prone 2.3.1 and NullAway 0.4.6.

Failed Travis CI build: https://travis-ci.org/dropwizard/dropwizard/jobs/394031326#L5906-L5912
Dropwizard repository: https://github.com/dropwizard/dropwizard/tree/959182092d57debcc0c85f74b895b33ccb073431
Source file which makes the build fail: [`io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java:[50,32]`](https://github.com/dropwizard/dropwizard/blob/959182092d57debcc0c85f74b895b33ccb073431/dropwizard-hibernate/src/test/java/io/dropwizard/hibernate/UnitOfWorkAwareProxyFactoryTest.java#L50)

Unfortunately I'm currently unable to provide a minimal example to reproduce the issue, but the build of dropwizard-hibernate reproducibly fails when analyzing `UnitOfWorkAwareProxyFactoryTest`.

### What did you expect to see?

The build should be successful or at least emit proper warnings by Error Prone/NullAway.

FWIW, the build succeeds with Error Prone 2.2.0 and NullAway 0.3.2.

### What did you see instead?

The build fails with a NullPointerException in NullAway.

The stack trace of the NullPointerException looks similar to the one in #144.

**Comment by lazaroclapp** [comment]
@joschi Thanks for the report! Definitely a bug in NullAway. I figured out a repro for this now. It is basically an interaction between the try-with-resources construct and our initialization detection code. 

We are working on an actual fix, which shouldn't take too long, but, as a workaround, adding `@SuppressWarnings("NullAway")` to that `setUp` method should cause NullAway to ignore it and thus not crash on it.

**Comment by lazaroclapp** [comment]
Should be fixed in master. Let me cut a release so you can test the fix, @joschi

**Comment by joschi** [comment]
@lazaroclapp The [build with NullAway 0.4.7](https://travis-ci.org/dropwizard/dropwizard/builds/394430062) is successful. 🎉

Thanks for your quick and awesome work!
