### ISSUE TITLE
Support Objects.isNull and !Objects.isNull for null checking

### ISSUE THREAD

**Issue by talios** [uber/NullAway#178]
We have some code looking like:

```java
if (!Objects.isNull(hikariDataSource)) {
  ...
}
```

however NullAway doesn't recognise the usage of `Objects.isNull` to guard against the nullity of the datasource, this is using 0.4.6 of NullAway. It would be nice is NullAway supported `java.util.Objects#isNull`.

**Comment by talios** [comment]
No real rush, we're not running with NullAway on by default at the moment and for now, I switched that check over in my branch.

**Comment by lazaroclapp** [comment]
Ok, this should be fixed on master and support will be out with 0.4.8. Closing this issue. Feel free to reopen if there is any problem, of course.
