### ISSUE TITLE
Add warning for unnecessary `CastToNonNullMethod` calls

### ISSUE THREAD

**Issue by lazaroclapp** [uber/NullAway#190]
When given `-XepOpt:NullAway:CastToNonNullMethod`, NullAway should warn whenever the argument to that method is `@NonNull`, to reduce unnecessary/redundant casts.

I am seeing a ton of those internally and we are just needlessly adding indirection and checks due to those. Relatively low priority, but I want to track this.

**Comment by msridhar** [comment]
I like it. Should be easy to provide an autofix as well.
