### ISSUE TITLE
Trailing comment after suppression

### ISSUE THREAD

**Issue by jbarr21** [uber/NullAway#212]
It would be helpful for migrations to be able to identify a new batch of nulls that need suppressing with the auto-suppresser until they can be addressed. It would be useful to be able to add a trailing line comment with a configurable message 
```java
@SuppressWarnings("NullAway") // T1234567
public void doSomething() {
  foo.bar();
}
```

**Comment by lazaroclapp** [comment]
@jbarr21 How does this look? https://github.com/uber/NullAway/pull/213/files#diff-7f652d10adf0edc2f1c37da1eb1ee9cbR36 (See test case)

It will actually look like:

```
@SuppressWarnings("NullAway") /* T1234567 */ public void doSomething() {
  foo.bar();
}
```

Or:

```
@SuppressWarnings("NullAway") /* T1234567 */
public void doSomething() {
  foo.bar();
}
```

**After** Google Java Format (using `/*...*/` because matching indentation was a pain otherwise).

**Comment by lazaroclapp** [comment]
Landed. Let me know if you want us to cut a release. We will likely do so anyways in a few days to incorporate some JarInfer changes, but if it helps you guys to have it sooner, it wouldn't be hard to do another release with just this change.

**Comment by jbarr21** [comment]
that timeframe sounds good to me

**Comment by msridhar** [comment]
Closing as I think this is done
