### ISSUE TITLE
Nested classes annotated with Excluded Class Annotation are still analysed.

### ISSUE THREAD

**Issue by marycha** [uber/NullAway#237]
Nested classes, static and non-static, marked to be excluded from nullness analyses, are still analysed.

```
-XepOpt:NullAway:ExcludedClassAnnotations=org.myorg.IgnoreNullsafety
```

```java
class OuterClass {

  @IgnoreNullsafety
  public static class NestedClass {
    private Object x;    // [ERROR] [NullAway] @NonNull field x not initialized
  }
}
```
NullAway version: 0.5.5

**Comment by msridhar** [comment]
Thanks for the report @marycha!  This is indeed a bug, and one that we could probably fix with some work.  I'm wondering about prioritization, though.  Does this come up often for you in your code base, or is this a common pattern when using some framework?  Even if it's not commonly used, it's weird that this feature doesn't work for inner classes so at the very least we should document the limitation.

**Comment by marycha** [comment]
thanks for quick answer @msridhar!

I just noticed the same happens if I annotate nested class with `@SuppressWarnings("NullAway.Init")`, works well with `@SuppressWarnings("NullAway")` though.

Regarding your question about usage and prioritisation, we have our custom dependency injection framework which uses nested Builder classes. So it's fairly common pattern in our codebase but may not be elsewhere and I can easily use `@SuppressWarnings("NullAway")` instead for these builders, they don't have any logic.

**Comment by marycha** [comment]
I opened also #238 as something that would work for this pretty well.
