### ISSUE TITLE
Error:java: NullAway is not a valid checker name in IntelliJ

### ISSUE THREAD

**Issue by perfectacle** [uber/NullAway#247]
* Mac OS X Mojave
* OpenJDK 10.0.1
* Error Prone 2.3.2
* Error Prone Gradle Plugin 0.6
* Nullaway 0.6.0
* IntelliJ IDEA 2018.2.4
* Error Prone IntelliJ IDEA Plugin 182.3911.36(Error Prone 2.3.1)

```groovy
plugins {
    id("net.ltgt.errorprone") version "0.6"
}

apply plugin: 'java'

sourceCompatibility = 10

repositories {
    mavenCentral()
}

dependencies {
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
    errorprone group: 'com.google.errorprone', name: 'error_prone_core', version: '2.3.2'
    annotationProcessor group: 'com.uber.nullaway', name: 'nullaway', version: '0.6.0'
}

import net.ltgt.gradle.errorprone.CheckSeverity

tasks.withType(JavaCompile) {
    options.errorprone {
        check("NullAway", CheckSeverity.ERROR)
        option("NullAway:AnnotatedPackages", "src")
    }
}
```

Gradle's compileJava task works fine!  
but IntelliJ IDEA's Javac with error-prone compiler not works.  

```bash
-XDcompilePolicy=byfile -Xep:NullAway:ERROR -XepOpt:NullAway:AnnotatedPackages=src
```
Error:java: NullAway is not a valid checker name

How can I fix it?

**Comment by msridhar** [comment]
@perfectacle did this ever work for you inside IntelliJ, or is this the first time you are trying?  I wonder if IntelliJ is not setting the processor path correctly.  @tbroyer any ideas here?

**Comment by perfectacle** [comment]
@msridhar It is first time
```bash
-XDcompilePolicy=byfile
```
It works fine (without any checker)

**Comment by tbroyer** [comment]
IntelliJ doesn't automatically configures the processor path from Gradle builds. There's an open issue on JetBrains side (https://youtrack.jetbrains.com/issue/IDEA-187868), but for now you'd have to configure the processor path manually (suggested workarounds wouldn't work for Error Prone custom checks).

Fwiw, I simply delegate build/run actions to Gradle, specifically so that I'm sure I don't have different configurations between the IDE and the actual build.

**Comment by msridhar** [comment]
Ok, I'm going to close as this is an IntelliJ issue

**Comment by hk0i** [comment]
> Fwiw, I simply delegate build/run actions to Gradle, specifically so that I'm sure I don't have different configurations between the IDE and the actual build.

Could you elaborate? How can I do this too? I hate that IDE and command line do things differently.

**Comment by tbroyer** [comment]
See https://www.jetbrains.com/help/idea/gradle.html#delegate_build_gradle

**Comment by hk0i** [comment]
Okay, I tried that and now I just realized it's only failing for my unit tests, and it still fails even for gradle command line builds for my android project.

Should I open a new issue for this?
Some more information:

[My `build.gradle`](https://gist.github.com/hk0i/47bd6a97129b3969fa33f282dcfe1272)

```
./gradlew --version

------------------------------------------------------------
Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          10 ("Oracle Corporation" 10+46)
OS:           Mac OS X 10.14 x86_64
```

---

```
./gradlew testDevDebugUnitTest
> Task :app:compileDevDebugUnitTestJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDevDebugUnitTestJavaWithJavac'.
> NullAway is not a valid checker name

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
37 actionable tasks: 1 executed, 36 up-to-date
```

**Comment by tbroyer** [comment]
You're adding NullAway only to `annotationProcessor`, but applying NullAway options to every `JavaCompile` tasks, including those for tests, which won't have NullAway in their processor path.

Either add NullAway to the `errorprone` configuration (instead of `annotationProcessor`) to have it available everywhere; or change your build to only configure NullAway for the _main_ variant (no idea how to do this though, I don't know the Android Gradle Plugin much)

**Comment by hk0i** [comment]
ah okay, that makes sense. Thanks.

For now I'll remove it for tests following the sample gradle instruction:

```groovy
tasks.withType(JavaCompile).configureEach {
    if (!name.toLowerCase().contains("test")) {
        // add for test only
        options.errorprone {
            // ...
        }
    }
}
```

This is good for now. I'll revisit later.
