### ISSUE TITLE
NullAway not recognized as an EP option in Android Gradle Plugin 3.x

### ISSUE THREAD

**Issue by hzsweers** [uber/NullAway#25]
Repro branch can be found here - https://github.com/uber/AutoDispose/tree/z/agp3testing1orchestrator

Compiling the arch components artifact will give an error that `NullAway` is not a recognized argument. Not sure if something changed with how this is handled as far as compiler args go in 3.x, but we should provide some guidance on this.

CC @kageiit

**Comment by kageiit** [comment]
Commented on the repro branch, but the configuration needs to be inside `afterEvaluate` block for it to work in AGP 3 as tasks are no longer created before hand

**Comment by hzsweers** [comment]
Updated the branch, still doesn't work even if it's put in an afterEvaluate block

**Comment by hzsweers** [comment]
Also - I think without `afterEvaluate` still works fine. I noticed I've been doing it outside of a block in a side project on AGP 3.0 and it's fine

**Comment by msridhar** [comment]
@hzsweers do we need to update the description here?  Or is there actually no bug?

**Comment by hzsweers** [comment]
Need to update the description for nullaway. First party EP checks work, NullAway doesn't it seems :|

**Comment by msridhar** [comment]
As a hack you can also pass `-XepIgnoreUnknownCheckNames` to the JVM.  My suspicion is that Gradle doesn't pass the NullAway jar on the processor path for some compilation task.  But you should also test that bugs are still getting caught; if not, then something more serious is messed up.

**Comment by hzsweers** [comment]
Alright I'll check and report back

**Comment by msridhar** [comment]
@hzsweers any update here?

**Comment by hzsweers** [comment]
Sorry forgot about this, I'll try today

**Comment by msridhar** [comment]
@hzsweers ping

**Comment by msridhar** [comment]
@hzsweers when I try to build your repro branch by running `./gradlew :android:autodispose-android-archcomponents:build` I get the following error:
```
* Where:
Build file '/Users/msridhar/git-repos/AutoDispose/sample/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating project ':sample'.
> Failed to apply plugin [id 'com.android.application']
   > The following project options are deprecated:
     com.android.build.threadPoolSize
     The com.android.build.threadPoolSize property has been replaced by android.threadPoolSize
```

How can I reproduce the problem?

**Comment by hzsweers** [comment]
Remove the deprecated line from ~/.gradle/gradle.properties, you probably have it from one of our old intelliJ plugins :|

Sorry I forgot about this. Let me know if you want me to look again

**Comment by msridhar** [comment]
So I fixed my gradle.properties and re-ran `./gradlew clean :android:autodispose-android-archcomponents:build` on the repro branch and it compiled fine (though I do get a whole mess of Javadoc errors).  Also the sample app in #76 uses AGP 3.x and it works fine.  @hzsweers can you still repro the problem?

**Comment by msridhar** [comment]
@hzsweers gonna close this out for housekeeping purposes, but please re-open if you manage to repro

**Comment by hzsweers** [comment]
Update - finally discovered the issue. It was not being added before because I didn't have it specified on `androidTestAnnotationProcessor`. This didn't pop up in the sample apps here either because they all ignore any configuration with `test` in the lowercase name :)
