### ISSUE TITLE
Use Gradle task to install pre-commit hook

### ISSUE THREAD

**Issue by msridhar** [uber/NullAway#297]
Right now we hack `gradlew` to install our formatting pre-commit hook.  #294 remove this in the process of doing a Gradle update.  But I think that's good; it was hackish anyway.  We should use a Gradle task to do the installation instead.  WALA's build.gradle shows how to do it:

https://github.com/wala/WALA/blob/96408b265b2b431f24b221104cfdb89be1c59fd8/build.gradle#L284-L295

We can then make some common Gradle task dependent on `installGitHooks` to install the hook automatically.

**Comment by lazaroclapp** [comment]
100% agreed, but let's not remove it from `.gradlew` until we have this set up, just for the sake of keeping master green even on new `git clone`s.
