### ISSUE TITLE
JarInfer bytecode rewriting should avoid adding redundant annotations

### ISSUE THREAD

**Issue by lazaroclapp** [uber/NullAway#340]
The `@Nullable` annotation is not repeatable. Currently, running JarInfer on libraries that already have annotations produces the following issue when processing with `D8`:

```
Error: Multiple annotations of type `javax.annotation.Nullable`
com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:72)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
	at com.android.tools.r8.D8.run(D8.java:73)
```

Suggestions:
1) Never duplicate an annotation. If `@Nullable` or `@NonNull` are already present on the input jar, keep them and don't add a redundant (or contradictory) annotation (fine to log an error in the second case).
2) We should consider providing a flag `--skip-annotated` that completely skips processing code that's already manually annotated. It's unclear to me at which level we should be looking, though. If we do full jar, we risk skipping many libraries because they fat-jar-include some class that has nullability annotations. An option would be to skip at the class level instead (e.g. any class that mentions `@Nullable` or `@NonNull` in the input jar is not re-written.

We don't need to implement these two at the same time. (1) is blocking internal deployment, (2) is a a nice to have :)

**Comment by navahgar** [comment]
Good points. I can take 1, if you are not already on it.

**Comment by lazaroclapp** [comment]
Go for it. Currently looking at the CI failure for #334

**Comment by lazaroclapp** [comment]
Hey @navahgar , are you still looking at this one? It's the current blocker for re-enabling JarInfer internally (possibly not the only one, but the one I am first seeing triggering). I can take a look too, but wanted to check with you first.

**Comment by shas19** [comment]
@navahgar Is this issue resolved with the PR #341?

**Comment by navahgar** [comment]
PR #341 fixed 1 but not 2. Currently, we are just ignoring the redundant annotations. Going forward, we have to figure out how to handle this best - error on such cases and / or add a flag to control this?

**Comment by navahgar** [comment]
I think that is a good state to close this at for now. If we need any other changes in future, we can look into them at that point.
