### ISSUE TITLE
Fragment onactivitycreated should be considered as initializer

### ISSUE THREAD

**Issue by david-gang** [uber/NullAway#344]
Thanks for using NullAway. Before you create an issue, please consider the following points:

  - [ ] If you think you found a bug, please include a code sample that reproduces the problem. A test case that reproduces the issue is preferred. A stack trace alone is ok but may not contain enough context for us to address the issue.
```
public class BlankFragment2 extends Fragment {
    private String mParam1;

    public BlankFragment2() {
        // Required empty public constructor
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        mParam1 = "Hello World";
    }
}
```

gives a compilation error 
> [NullAway] initializer method does not guarantee @NonNull field mParam1 is initialized along all control-flow paths (remember to check for exceptions or early returns).

As stated in the [android documentation](https://developer.android.com/reference/android/support/v4/app/Fragment.html#onActivityCreated(android.os.Bundle))
> It can be used to do final initialization once these pieces are in place, such as retrieving views or restoring state.

So it just makes sense to have this as initializer
  - [ ] Please include the library version number, including the minor and patch version, in the issue text.
I am using version:0.7.5

**Comment by msridhar** [comment]
This makes sense to me.  @david-gang if you have time to submit a PR the relevant code is here:

https://github.com/uber/NullAway/blob/d617d0ca433d06829c9749b50b6d2e054f672ca4/nullaway/src/main/java/com/uber/nullaway/ErrorProneCLIFlagsConfig.java#L76-L100

**Comment by david-gang** [comment]
cool. will do. Is there some unit test which i should consider to write? where does it exist?
