### ISSUE TITLE
Preconditions.checknotnull not supoorted when using the template option

### ISSUE THREAD

**Issue by david-gang** [uber/NullAway#354]
Thanks for using NullAway. Before you create an issue, please consider the following points:

  - [x] If you think you found a bug, please include a code sample that reproduces the problem. A test case that reproduces the issue is preferred. A stack trace alone is ok but may not contain enough context for us to address the issue.
Preconditions checknotnull comes with a template flavor to save cpu cycles:
https://guava.dev/releases/snapshot/api/docs/src-html/com/google/common/base/Preconditions.html#line.918

add to NullAwayNegtaiveTestCases the following function:
```
static void checkNotNullWithMessageTemplate(Map<String,Object> map) {
    String name = "Mister x";
    Object o = map.get(name);
    Preconditions.checkNotNull(o, "Object for %s should exist", name);
    o.toString();
  }
```
 It will blow up
  - [x] Please include the library version number, including the minor and patch version, in the issue text.

0.7.6

**Comment by david-gang** [comment]
It all boils down to 

```
private static final ImmutableSetMultimap<MethodRef, Integer> FAIL_IF_NULL_PARAMETERS =
        new ImmutableSetMultimap.Builder<MethodRef, Integer>()
            .put(methodRef("com.google.common.base.Preconditions", "<T>checkNotNull(T)"), 0)
            .put(
                methodRef(
                    "com.google.common.base.Preconditions", "<T>checkNotNull(T,java.lang.Object)"),
                0)
            .put(methodRef("java.util.Objects", "<T>requireNonNull(T)"), 0)
            .put(methodRef("java.util.Objects", "<T>requireNonNull(T,java.lang.String)"), 0)
            .put(methodRef("org.junit.Assert", "assertNotNull(java.lang.Object)"), 0)
            .put(
                methodRef("org.junit.Assert", "assertNotNull(java.lang.String,java.lang.Object)"),
                1)
            .put(
                methodRef("org.junit.jupiter.api.Assertions", "assertNotNull(java.lang.Object)"), 0)
            .put(
                methodRef(
                    "org.junit.jupiter.api.Assertions",
                    "assertNotNull(java.lang.Object,java.lang.String)"),
                0)
            .put(
                methodRef(
                    "org.junit.jupiter.api.Assertions",
                    "assertNotNull(java.lang.Object,java.util.function.Supplier<java.lang.String>)"),
                0)
            .build();
```

How do i express here varargs ?

**Comment by msridhar** [comment]
@david-gang thanks for the report.  At the bytecode level, varargs show up as an `Object[]` argument I believe.  So maybe you can test adding that signature?  A PR would be welcome!

**Comment by david-gang** [comment]
Ok, good and bad news. I found how to fix the issue but there are ~20 flavors of this function.
I started to fix the issue in my branch:
here are the test cases.
```
static void checkNotNullWithMessageTemplate(@Nullable Object o1, @Nullable Object o2, @Nullable Object o3,
                                              @Nullable Object o4
                                              ) {
    Preconditions.checkNotNull(o1, "%s", "a");
    o1.toString();

    Preconditions.checkNotNull(o2, "%s %s", "a", "b");
    o2.toString();

    Preconditions.checkNotNull(o3, "%s %s %s", "a", "b", "c");
    o3.toString();

    Preconditions.checkNotNull(o4, "%s %s %s %s", "a", "b", "c", "d");
    o4.toString();
  }
```

and also the configurations are added as follows:

```
static void checkNotNullWithMessageTemplate(@Nullable Object o1, @Nullable Object o2, @Nullable Object o3,
                                              @Nullable Object o4
                                              ) {
    Preconditions.checkNotNull(o1, "%s", "a");
    o1.toString();

    Preconditions.checkNotNull(o2, "%s %s", "a", "b");
    o2.toString();

    Preconditions.checkNotNull(o3, "%s %s %s", "a", "b", "c");
    o3.toString();

    Preconditions.checkNotNull(o4, "%s %s %s %s", "a", "b", "c", "d");
    o4.toString();
  }
```
so it works but:

* is not nice
* is tedious and makes the code long.

Is this the right way to go?

Before going this way down i want to be sure that i am doing the right thing.

**Comment by msridhar** [comment]
Looking at [the source code](https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Preconditions.java) it looks like there are a boatload of overloads for `checkNotNull`.  Unfortunately I think we need to add one `methodRef` per overload to our configuration; there's no easy way around it.

I would prefer to bite the bullet and just support all of these overloads in one PR.  I don't think we need a test for every single overload, though, if that helps.  If it's too much to handle all of them, you can submit a PR handling the ones you care about most, with a comment indicating there are more to support.
