### ISSUE TITLE
Maven wiki snippet missing </plugins>

### ISSUE THREAD

**Issue by JakeWharton** [uber/NullAway#358]
See https://github.com/uber/NullAway/wiki/Configuration#maven

```xml
      </plugin>
  </build>
```
should be:
```diff
       </plugin>
+    </plugins>
   </build>
```

**Comment by lazaroclapp** [comment]
Good catch! Should be fixed now.

As the song goes... "CS will make each day a quest to find a missing close-paren." 😅
