### ISSUE TITLE
String operators omit null analysis

### ISSUE THREAD

**Issue by david-gang** [uber/NullAway#373]
Thanks for using NullAway. Before you create an issue, please consider the following points:

  - [ ] If you think you found a bug, please include a code sample that reproduces the problem. A test case that reproduces the issue is preferred. A stack trace alone is ok but may not contain enough context for us to address the issue.
```
private void test(@Nullable String s){
        String s1 = s+ "a";
    }
```
this does not fail

This is the same as:
```
String s1 = s.concat("a");
```

which fails. so operrator handling is missing

  - [ ] Please include the library version number, including the minor and patch version, in the issue text.
0.7.9

**Comment by Stephan202** [comment]
While the result of `s + "a"` is probably undesirable for `s == null`, it is not the same as `s.concat("a")`:

```
jshell> String s = null
s ==> null

jshell> s.concat("a")
|  Exception java.lang.NullPointerException
|        at (#2:1)

jshell> s + "a"
$3 ==> "nulla"
```

**Comment by david-gang** [comment]
ok. thanks for the explaination. will close

**Comment by lazaroclapp** [comment]
Just to add to this, briefly, we could add a warning/error for this case, but the "nulla" result above unfortunately sometimes _is_ what you want, e.g.:

```
System.err.println("Debug print for object foo: " + foo);
```

The result: "Debug print for object foo: null" is perfectly useful, whereas a nullness warning that stops compilation might not be.
