### ISSUE TITLE
Any alternative for Objective-C nullable check like NullAway?

### ISSUE THREAD

**Issue by foobra** [uber/NullAway#376]
NullAway is great, we use it everyday. We both have iOS project which need alternative like NullAway, Any suggestions? Thanks

**Comment by shas19** [comment]
I think [Infer](https://github.com/facebook/infer) works for objective C. Though it could be much slower. 

NullAway [paper](https://arxiv.org/pdf/1907.02127.pdf) has some information about NullAway project build time(1.15 times original) and Infer project build time (2.83 times original). I am not sure if there is any faster Objective-C checker.

**Comment by msridhar** [comment]
@foobra so glad NullAway is working for you!  For Objective-C, the other option I know of is the [Clang Static Analyzer](https://clang-analyzer.llvm.org/), which I think does some nullability checking.  Also it looks like XCode itself [has some support](https://developer.apple.com/swift/blog/?id=25) as part of interop with Swift.  But I don't have too much experience there.  And as @shas19 indicates, I'm not sure there is any option just like NullAway that gives more complete coverage and integrates with the compiler.

**Comment by msridhar** [comment]
I'll close for now but re-open if there is a NullAway issue here
