### ISSUE TITLE
Nullaway does't take thrown Exception into account

### ISSUE THREAD

**Issue by hupfdule** [uber/NullAway#385]
I am using nullaway 0.7.9.

Please see this example code snippet:

```java
import java.util.concurrent.atomic.AtomicReference;

public class Test {

  private final AtomicReference<String> ref= new AtomicReference();

  public void start() {
    synchronized(this.ref){
      final String s= this.ref.get();
      if (s != null){
        throw new IllegalStateException("ref is not set");
      }

      doSomething(s);
    }
  }

  public void doSomething(final String s) {
    System.out.println(s);
  }
}
```

I would expect this code to be compiled without problems, since a check for null is made via `if (s != null)` and then an exception is thrown. The value passed to `doSomething()` can never be null.

However nullaway insists that `doSomething(s)` could use a null value:

```
[NullAway] passing @Nullable parameter 's' where @NonNull is required
```

Is this done deliberately? Is this considered a bug?

**Comment by msridhar** [comment]
Did you mean `if (s == null)`?

**Comment by hupfdule** [comment]
Damn! There was a _real_ bug in the code where we triggered that. I just copied the bug into my example above.

Therefore: nullaway is working file. It actually did what is should and provided us with the correct error.

Sorry for bothering.

**Comment by msridhar** [comment]
No problem, glad to hear NullAway is working for you!
