### ISSUE TITLE
Wrong option to enable auto suppressing (SuggestSuppressions)

### ISSUE THREAD

**Issue by joschi** [uber/NullAway#386]
Error Prone 2.3.4
NullAway 0.7.9

The wiki page at https://github.com/uber/NullAway/wiki/Suppressing-Warnings#auto-suppressing says:

> If you pass the option `-Xep:NullAway:SuggestSuppressions=true` to NullAway, it will use Error Prone's suggested fix functionality to suggest suppressing any warning that it finds. 

The correct option is `-XepOpt:NullAway:SuggestSuppressions=true`, but unfortunately I'm unable to fix this in the wiki directly.

**Comment by msridhar** [comment]
Fixed; thanks!
