### ISSUE TITLE
NullAway not working after upgrading to latest version

### ISSUE THREAD

**Issue by leinardi** [uber/NullAway#395]
After upgrading NullAway form version `0.7.5` to version `0.7.10`, it doesn't work anymore.

All the changes are visible in this commit: https://github.com/leinardi/FloatingActionButtonSpeedDial/commit/69796f21b345f1b8cbbffbeb9b018a75cbce4392

It is possible to reproduce the issue using the `nullaway` branch:
https://github.com/leinardi/FloatingActionButtonSpeedDial/tree/nullaway

I simply added the code from the plugin README [to one my classes](https://github.com/leinardi/FloatingActionButtonSpeedDial/commit/6f8d69d7ecaeb2a1d6810df4ebee2067ef00484b):
```
static void log(Object x) {
    System.out.println(x.toString());
}
static void foo() {
    log(null);
}
```
And I'm expecting to see errors after running `./gradlew build` but, instead, it build successfully.

**Comment by msridhar** [comment]
@leinardi looks like you bumped a lot of deps at once, which makes this a bit tricky to track down.  Can you confirm that Error Prone itself is still running and detecting errors?  Also, can you confirm that if you keep NullAway  at `0.7.5` but retain all the otherversion bumps in your commit, NullAway still works?

**Comment by lazaroclapp** [comment]
I see this line:

```
option("NullAway:AnnotatedPackages", "com.leinardi.android.speeddial")
```

It might not be the only thing, but don't you mean:

```
option("XepOpt:NullAway:AnnotatedPackages", "com.leinardi.android.speeddial")
```

Or similar? Pretty sure the Error Prone option prefix (`-XepOpt:`) still has to show up somewhere as that's not a `javac` option.

**Comment by talios** [comment]
I noticed issues with NullAway yesterday after upgrading to the latest error_prone_core (2.4.0) release, which changes the annotations used when writing e_p checks (I had to remove an attribute from my own custom checks when upgrading) so there MAY be an issue specifically with the new error prone release.

What version of e_p is the gradle plugin using?

I suspect the 2.4.0 issue I saw may be unrelated (I came to see if anyone had raised an issue, and to raise one if not, but thought I'd comment here also).

**Comment by leinardi** [comment]
I manage to fix the issue: I was missing the dependencies
```
  errorprone "com.google.errorprone:error_prone_core:2.3.2"
  errorproneJavac "com.google.errorprone:javac:9+181-r4173-1"
```
Before both NullAway and ErrorProne worked fine without, now it seems it's mandatory.

It seems to work fine also with ErrorProne 2.4.0 and gradle-errorprone-plugin plugin 1.2.1.

**Comment by leinardi** [comment]
I suggest you to update the examples linked in the Android section of the README because they are both missing some or all these dependencies:
![image](https://user-images.githubusercontent.com/273338/83397478-fb83e580-a3fd-11ea-9500-9a18c52c870e.png)

https://github.com/uber/NullAway/blob/56d1df233bb3383f23f3e3a2e0c134c621144496/sample-app/build.gradle#L68

https://gist.github.com/msridhar/6cacd429567f1d1ad9a278e06809601c#file-nullaway-build-gradle-L40

**Comment by leinardi** [comment]
@msridhar README and Gist look good, but what about the sample-app? Is still missing the dependencies and is linked in the Android section of the Doc: https://github.com/uber/NullAway/blob/master/sample-app/build.gradle

**Comment by msridhar** [comment]
The sample app inherits some configuration from the main `build.gradle`:

https://github.com/uber/NullAway/blob/4645867c0cf9c2c867d1446affc691d692faac6d/build.gradle#L43-L47

So it's not great for direct copy-pasting.  I will note this in the README.
