### ISSUE TITLE
Spring's @Autowired should probably be an external initialization annotation

### ISSUE THREAD

**Issue by lazaroclapp** [uber/NullAway#396]
That is: `org.springframework.beans.factory.annotation.Autowired`

Writing this mostly as a reminder to self. But if anyone else wants to do it, it should be a trivial change.

**Comment by vasantteja** [comment]
Happy to help.

**Comment by lazaroclapp** [comment]
Go for it @vasantteja !

All it needs is to be added to [this list](https://github.com/uber/NullAway/blob/master/nullaway/src/main/java/com/uber/nullaway/ErrorProneCLIFlagsConfig.java#L110), and then a unit test or two :)

**Comment by koneko096** [comment]
Hi @vasantteja any update on it?

**Comment by chat-eau-lumi** [comment]
Hi, I wanted to pick this issue up- should the unit test go in CheckFieldInitNegativeCases.java?

**Comment by msridhar** [comment]
Looking at the [Javadoc](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/annotation/Autowired.html) it seems `@Autowired` can go on either fields or methods.  For fields, I think `@Autowired` should mean the field is excluded from initialization checking, i.e., the annotation should be added to [this list](https://github.com/uber/NullAway/blob/dba4c2d9fcdd15e1928955a5a0d706405757435e/nullaway/src/main/java/com/uber/nullaway/ErrorProneCLIFlagsConfig.java#L116-L121).  

I _think_ an `@Autowired` method should be treated as an initializer, based on [this tutorial](https://www.baeldung.com/spring-autowire).  If that's right,  the annotation can be added to [this list](https://github.com/uber/NullAway/blob/dba4c2d9fcdd15e1928955a5a0d706405757435e/nullaway/src/main/java/com/uber/nullaway/ErrorProneCLIFlagsConfig.java#L107-L112) which @lazaroclapp linked above.

For both cases, I think the test should be a new test method at the bottom of `NullAwayTest` in the same style as the more recent tests (with inline source code as a string).  We really need to refactor `NullAwayTest` (see #430) but that doesn't need to be part of a PR for this issue.

**Comment by lazaroclapp** [comment]
I agree with @msridhar on every particular here. Wonder if having the annotation in both default lists will cause an issue, but that's what the unit tests will be for. If it does seem to be causing a conflict, let me know and I can help you dig further into that code, but ideally it should work with just that 🙂

**Comment by chat-eau-lumi** [comment]
Trying to put the test in NullAwayTest, but the line "@Autowired" causes an AssertionErrorWithFacts. I'm assuming this is because Spring isn't in the test build- where do I fix this? I tried putting a Spring Boot plugin in dependencies.gradle/(test) settings.gradle, didn't seem to work.

**Comment by lazaroclapp** [comment]
@chat-eau-lumi Care to share a PR or at least the full stack trace for that error? 🙂

**Comment by chat-eau-lumi** [comment]
See above!

**Comment by chat-eau-lumi** [comment]
I should also mention that it might be more of an integrated test than a unit test- I'm not very sure how much Spring does here.

**Comment by msridhar** [comment]
I think this was fixed by #477
