### ISSUE TITLE
Support optional.orElse(null)

### ISSUE THREAD

**Issue by Garciat** [uber/NullAway#406]
This will pass as non-null:

```java
Optional.<Object>empty().orElse(null)
```

For example:

```java
class Example {
  void f(Object o) {}

  void fails() {
    f(null);
  }

  void passesButShouldnt() {
    f(Optional.<Object>empty().orElse(null));
  }
}
```

I would expect `anything.orElse( ... something Nullable ...)` to be inferred to be Nullable.

**Comment by msridhar** [comment]
@lazaroclapp I think we could handle this with a `@Contract` annotation.  Maybe we can do it as a library model?

**Comment by lazaroclapp** [comment]
> @lazaroclapp I think we could handle this with a `@Contract` annotation. Maybe we can do it as a library model?

Funny you should ask. I am about done with a PR that allows to encode the same semantics as `@Contract(!null -> !null)` as a library model ;)

**Comment by lazaroclapp** [comment]
@Garciat This has now been fixed in master, we will try to cut a new version of NullAway with the fix (and the Error Prone upgrade) soon.

**Comment by Garciat** [comment]
Thanks! That was super quick 🙏
