### ISSUE TITLE
Move from Travis CI to GitHub actions

### ISSUE THREAD

**Issue by lazaroclapp** [uber/NullAway#408]
Probably worth doing when possible, as per @tyvsmith's advice 😁

**Comment by msridhar** [comment]
Is there a brief explanation anywhere of the advantages?

**Comment by msridhar** [comment]
> Is there a brief explanation anywhere of the advantages?

For my own future reference, I think resource limitations on Travis CI are a good enough reason to move.  Also, switching to GitHub Actions will let us easily run tests on Windows.

**Comment by sherrif10** [comment]
Travis CI  is still the better and is being used my many big organisations however i would like to work on this if you give me a go ahead cc @msridhar  @lazaroclapp

**Comment by msridhar** [comment]
Thanks for the offer, @sherrif10!  But, I think it will be easier for a maintainer still at Uber like @lazaroclapp to take care of this one, as it requires dealing with permissions to set up GitHub Actions, adding credentials to set up snapshot build uploading, etc.
