### ISSUE TITLE
Why not using kotlin so far ??

### ISSUE THREAD

**Issue by mIbrahim017** [uber/NullAway#41]
Thanks for using NullAway. Before you create an issue, please consider the following points:

  - [x] If you think you found a bug, please include a code sample that reproduces the problem. A test case that reproduces the issue is preferred. A stack trace alone is ok but may not contain enough context for us to address the issue.

  - [x] Please include the library version number, including the minor and patch version, in the issue text.

**Comment by msridhar** [comment]
Not really an issue.  See [here](https://www.reddit.com/r/androiddev/comments/77fr6r/engineering_nullaway_ubers_open_source_tool_for/) for discussion
