### ISSUE TITLE
Some fields are considered to nullable even though it has been initialize in constructor.

### ISSUE THREAD

**Issue by zhongyehong** [uber/NullAway#417]
```java
public class TestNullaway {
    private Object mA;
    private Object mB;
    private Object mC;

    public TestNullaway() {
        mA = new Object();
        init();
    }

    private void init() {
        mB = new Object();
        init2();
    }

    private void init2() {
        mC = new Object();
    }
}
```

mA, mB are considered to nonnull, but mC are considered to nullable

**Comment by msridhar** [comment]
Hi @zhongyehong, this is a known limitation of NullAway.  We have found it sufficient for nearly all code to only detect initialization in methods invoked _directly_ by a constructor, so we have not handled initialization from deeper call chains.  I updated the documentation [here](https://github.com/uber/NullAway/wiki/Error-Messages#initializer-method-does-not-guarantee-nonnull-field-is-initialized--nonnull-field--not-initialized) to clarify this point.  I think it's unlikely we will enhance this handling in the near future, but if you can point us at common code patterns where this is occurring, we may rethink it.  Thanks!
