### ISSUE TITLE
Break up NullAwayTest into multiple test classes

### ISSUE THREAD

**Issue by lazaroclapp** [uber/NullAway#430]
This file is enormous. Also, breaking it up will make running tests faster since Gradle can run separate test classes in parallel.

**Comment by msridhar** [comment]
I've created an initial plan below for splitting up `NullAwayTest`.  There is a list of test "themes" along with all the tests I think belong in that theme.  The tests in each theme could be moved into a new smaller test class, like this one I created recently: https://github.com/uber/NullAway/blob/master/nullaway/src/test/java/com/uber/nullaway/NullAwayUnsoundnessTests.java

The categorization may not be perfect, but it'll be a big improvement over what we have now.

I'm not sure that GitHub's rendering of the source code links as code snippets is helpful here, but you can see the relevant line numbers so hopefully it's good enough.  I can also try to paste the info as unrendered if desired.

* Skipped / unannotated code
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L101-L109
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L116-L170
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L372-L396
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L927-L957
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L2277-L2318

* Framework / library model support
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L111-L114
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L172-L179
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L242-L260
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L1122-L1138
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L2632-L2735
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L3039-L3151

* Initialization
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L181-L189
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L272-L286
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L293-L370
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L669-L687

* Java 8
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L232-L240
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L262-L270

* Contracts
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L208-L230
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L430-L667

* Thrift
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L718-L855

* Bytecode interactions
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L973-L1047

* Try constructs
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L288-L291
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L1049-L1120

* Test assertion libs
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L1140-L1371

* AcknowledgeRestrictiveAnnotations
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L398-L428
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L1424-L1677
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L2547-L2585

* Optional emptiness
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L1679-L2178

* Access paths
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L2342-L2452

* Varargs
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L2454-L2545

* RequiresNonNull / EnsuresNonNull
  * https://github.com/uber/NullAway/blob/bde8d50fb51e41ab1e3440f6f94b1d63168f207a/nullaway/src/test/java/com/uber/nullaway/NullAwayTest.java#L2737-L3037

**Comment by msridhar** [comment]
@Gellert5225 please take a look at this one

**Comment by msridhar** [comment]
This was fixed by #550
