### ISSUE TITLE
Support static fields in @EnsuresNonnull/@RequiresNonnull annotations

### ISSUE THREAD

**Issue by lazaroclapp** [uber/NullAway#431]
Follow up for #423, which punts when the field is not an instance field.

**Comment by agrieve** [comment]
+1, this would be great! Looking at adopting NullAway in Chrome, which tends to use a lot of statics, and hit the need for this pretty quickly.

**Comment by msridhar** [comment]
Cool use case!  We'll try to work on this in the near future.

**Comment by agrieve** [comment]
That's awesome! Been so far quite impressed with this project. Build speed is very important, so I love the focus. jspecify via `.astubx` seems promising as well!

I've been trying to chart a path towards annotating the codebase with `NullAwayAnnotator`, which if you're curious about (or have any feedback on), I've [added here](https://docs.google.com/document/d/1KNKs7jI8uoBLfBq4HCuGTYPLuTOMgUEuKrzyCUFjEk8/edit?tab=t.0).
