### ISSUE TITLE
can NullAway use CollectionUtils.isEmpty as a valid null check?

### ISSUE THREAD

**Issue by pablogrisafi1975** [uber/NullAway#435]
I got a dereferencing error in this code

```
if (!CollectionUtils.isEmpty(var)) {
     var.stream()...
} else {
    log.info("var is null or empty")
}
```

CollectionUtils.isEmpy, StringUtils.isEmpty, StringUtils.isBlank  are used everythere in our code, and while I think noone shoud ever use null collections, in real world code lots of time people use null Strings and Collections. In this particular case using var != null will get almost the same result, but you get the idea. Can NullAway consider some specific methods as valid null checks?

Thanks for this wonderfull tool!

**Comment by msridhar** [comment]
@pablogrisafi1975 what library does `CollectionUtils` and `StringUtils` come from?  We already some relevant `StringUtils` models here:

https://github.com/uber/NullAway/blob/d7e96e471df5c3420301ba782a3ac59b3ae1430a/nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java#L465-L475

Maybe we just need to add `CollectionUtils`?

**Comment by pablogrisafi1975** [comment]
You are probably right. I thought I was using apache commons but no.

- org.springframework.util.CollectionUtils.isEmpty
- spark.utils.StringUtils.isBlank
- spark.utils.StringUtils.isNotBlank
- spark.utils.StringUtils.isEmpty
- spark.utils.StringUtils.isNotEmpty
- spark.utils.StringUtils.hasLength

Maybe  org.apache.commons.lang3.StringUtils.isNull/Empty/Blank should be in NULL_IMPLIES_FALSE_PARAMETERS?

Thanks again

**Comment by msridhar** [comment]
That sounds like a good change to me. If you want to submit a PR for this we'd be happy to take a look!

**Comment by pablogrisafi1975** [comment]
ok, give me a couple of days....

**Comment by pablogrisafi1975** [comment]
took more than I expected, gradle is not my thing, but
https://github.com/uber/NullAway/pull/436
