### ISSUE TITLE
false positive result on fields injected using Dagger 

### ISSUE THREAD

**Issue by yashasvigirdhar** [uber/NullAway#44]
Version : 0.1.6

I've a lot of Android component classes where I use Dagger field injection. Getting error while running NullAway on them : 

`warning: [NullAway] @NonNull field <fieldName> not initialized`.

Am I missing some parameter to pass to error prone?

**Comment by yashasvigirdhar** [comment]
my bad !

Didn't realise that they should all be annotated with `@Nullable`. 

But then if I do that, it'd throw error whenever I try to use/dereference them anywhere, right? Or it detects if I've injected those fields/views or not?

**Comment by msridhar** [comment]
Have you seen `-XepOpt:NullAway:ExcludedFieldAnnotations` (see [here](https://github.com/uber/NullAway/wiki/Configuration))?  We pass `-XepOpt:NullAway:ExcludedFieldAnnotations=javax.inject.Inject,butterknife` when we run NullAway internally.  Does that solve the problem?

**Comment by msridhar** [comment]
Also we do *not* annotate those fields as `@Nullable`; as you point out, that would force a bunch of unnecessary null checks.

**Comment by yashasvigirdhar** [comment]
Oh yes ! I am sorry I missed that while going through the docs. It works !

Thanks for the prompt reply :) 

Of course, marking them as `@Nullable` won't be a good thing to do.

> Have you seen -XepOpt:NullAway:ExcludedFieldAnnotations (see here)? We pass -XepOpt:NullAway:ExcludedFieldAnnotations=javax.inject.Inject,butterknife when we run NullAway internally. Does that solve the problem?
