### ISSUE TITLE
Unrelease artifacts in test scope

### ISSUE THREAD

**Issue by hanson76** [uber/NullAway#456]
nullaway 0.9.0 (and probably earlier versions) includes dependencies in test scope that are unreleased (version is set to unreleased)

This cause problems when loading maven project into Intellij IDEA if the
projects pom.xml declares nullawy in the maven-compile-plugins <annotationProcessorPaths> section.

Intellij comlains about not being able to transfer artifact NullAway:test-java-lib:pom:unspecified from maven central.
This error causes Intellij to not add the Errorprone or Nullaway dependencies to the annotation process paths when 
compiling. Compiling fails with "java: plug-in not found: ErrorProne"

This is probably a bug in Intellij, but I think that it the nullaway pom.xml file should be clean up on release to not include
any test artifacts that are unreleased.

**Comment by msridhar** [comment]
@hanson76 thanks for the report.  Just wanted to let you know we saw it and @lazaroclapp and I are working on it.

**Comment by lazaroclapp** [comment]
Testing with the publish plugin changes from #457 , the dependency section from [this pom file](https://repo1.maven.org/maven2/com/uber/nullaway/nullaway/0.9.0/nullaway-0.9.0.pom) from 0.9.0 will now look like:

```
<dependencies>
  <dependency>
  <groupId>org.checkerframework</groupId>
  <artifactId>dataflow</artifactId>
  <version>3.6.0</version>
  <scope>runtime</scope>
  </dependency>
  <dependency>
  <groupId>org.checkerframework</groupId>
  <artifactId>javacutil</artifactId>
  <version>3.6.0</version>
  <scope>runtime</scope>
  </dependency>
  <dependency>
  <groupId>com.google.guava</groupId>
  <artifactId>guava</artifactId>
  <version>22.0</version>
  <scope>runtime</scope>
  </dependency>
</dependencies>
```

Without `test-java-lib` or other unpublished test dependencies.

**Comment by lazaroclapp** [comment]
Should be fixed with the next NullAway release. @hanson76 How much of a nuisance is that pom file on your end? We could consider cutting NullAway 0.9.1 with this change plus the limited JDK 15 fixes from #374, once those are ready, but only if it is needed. If not, well, this should be the last version with this problem.

**Comment by hanson76** [comment]
A 0.9.1 had been nice unless next version is planned to be released soon (week(s) not months from now), we currently have to do tricks with Intellij whenever we reload maven projects that uses NullAway.

**Comment by lazaroclapp** [comment]
@hanson76 Understood! We'll try to have 0.9.1 up this week or the next, depending on the status of the other open PR. Leaving this open until then.

**Comment by talios** [comment]
I see error-prone 2.6.0 has been released to maven central, it's not showing up on search.maven.org yet but turned up in my dependency watch list just now.

Can confirm that 0.9 works fine against it, but might be good to give a sanity test against that version before releasing.

**Comment by hanson76** [comment]
Any progress on this?

**Comment by msridhar** [comment]
@hanson76 we ran into a few issues cutting the release artifact due to #457 that we didn't catch before.  We are almost done working through them and hope to cut 0.9.1 soon

**Comment by lazaroclapp** [comment]
@hanson76 NullAway 0.9.1 was released last night and should fix the issue. At least based on [this](https://repo1.maven.org/maven2/com/uber/nullaway/nullaway/0.9.1/nullaway-0.9.1.pom) pom.xml file. Please try it when you can and confirm that this is resolved 🙂

**Comment by hanson76** [comment]
Verified and can confirm that it is resolved. 
Thank you for the fix!

**Comment by lazaroclapp** [comment]
Awesome. Np. Closing this task, then 🙂
