### ISSUE TITLE
Builder use case

### ISSUE THREAD

**Issue by xenoterracide** [uber/NullAway#465]
so, creating a builder will generally require field level nullables, depending on how you do it. I've got this

```java
/*
 * Copyright © 2021 Caleb Cushing.
 * Apache 2.0. See https://github.com/xenoterracide/brix/LICENSE
 * https://choosealicense.com/licenses/apache-2.0/#
 */
package com.xenoterracide.brix.configloader.api;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;
import org.checkerframework.checker.nullness.qual.MonotonicNonNull;
import org.checkerframework.checker.nullness.qual.Nullable;

import java.nio.file.Path;
import java.util.Map;
import java.util.Objects;

public class ProcessedFileConfiguration {

  private final Map<String, @Nullable Object> context;

  private final @Nullable Boolean overwrite;

  private final @Nullable Path source;

  private final Path destination;

  ProcessedFileConfiguration(
    Map<String, @Nullable Object> context,
    @Nullable Boolean overwrite,
    @Nullable Path source,
    Path destination
  ) {
    this.context = context;
    this.overwrite = overwrite;
    this.source = source;
    this.destination = destination;
  }

  public static Builder builder() {
    return new Builder();
  }

  public Map<String, @Nullable Object> getContext() {
    return context;
  }

  public @Nullable Boolean getOverwrite() {
    return overwrite;
  }

  public @Nullable Path getSource() {
    return source;
  }

  @Override
  public String toString() {
    return ToStringBuilder.reflectionToString( this, ToStringStyle.MULTI_LINE_STYLE );
  }

  public Path getDestination() {
    return destination;
  }

  @SuppressWarnings("checkstyle:HiddenField")
  public static final class Builder {
    private Map<String, @Nullable Object> context = Map.of();

    private @Nullable Boolean overwrite;

    private @Nullable Path source;

    private @MonotonicNonNull Path destination;

    private Builder() {
    }

    public Builder context( Map<String, @Nullable Object> context ) {
      this.context = context;
      return this;
    }

    public Builder overwrite( @Nullable Boolean overwrite ) {
      this.overwrite = overwrite;
      return this;
    }

    public Builder source( @Nullable Path source ) {
      this.source = source;
      return this;
    }

    public Builder destination( Path destination ) {
      this.destination = destination;
      return this;
    }

    public ProcessedFileConfiguration build() {
      var dest = Objects.requireNonNull( destination, "destination" );
      return new ProcessedFileConfiguration( context, overwrite, source, dest );
    }
  }
}
```

with the error, which is garbage, should I make another bug?

```
/home/xeno/IdeaProjects/brix/config-loader/api/src/main/java/com/xenoterracide/brix/configloader/api/ProcessedFileConfiguration.java:74: error: [NullAway] initializer method does not guarantee @NonNull field destination (line 72) is initialized along all control-flow paths (remember to check for exceptions or early returns).
    private Builder() {
            ^
    (see http://t.uber.com/nullaway )
```

the problem of course is the fact that I'm using checker frameworks `@MonotonicNonNull` which nullaway doesn't recognize. This probably actually isn't remotely useful for me but seems more correct.  I don't have a great way to handle this with nullaway,  though. I'm not certain that I'm asking for support of these annotations, or what I'm asking for, but perhaps such a use case could be handled better.

```
❯ ./gradlew dependencies | grep errorprone | sort -u && ./gradlew dependencies | grep nullaway | sort -u && ./gradlew --version              # brix -> ccushing/copy-5 !
|    +--- com.google.errorprone:error_prone_annotation:2.6.0
|    |    +--- com.google.errorprone:error_prone_annotation:2.6.0 (*)
|    |    +--- com.google.errorprone:error_prone_annotations:2.3.4
|    |         +--- com.google.errorprone:error_prone_annotations:2.3.4 -> 2.6.0
|    |         \--- com.google.errorprone:error_prone_annotations:2.4.0 -> 2.6.0
|    +--- com.google.errorprone:error_prone_annotations:2.6.0
|    |    +--- com.google.errorprone:error_prone_annotations:2.6.0
+--- com.google.errorprone:error_prone_annotations:{strictly 2.3.4} -> 2.3.4 (c)
+--- com.google.errorprone:error_prone_annotations:{strictly 2.6.0} -> 2.6.0 (c)
+--- com.google.errorprone:error_prone_annotation:{strictly 2.6.0} -> 2.6.0 (c)
|    +--- com.google.errorprone:error_prone_check_api:2.6.0
+--- com.google.errorprone:error_prone_check_api:{strictly 2.6.0} -> 2.6.0 (c)
+--- com.google.errorprone:error_prone_core:2.+ -> 2.6.0
+--- com.google.errorprone:error_prone_core:{strictly 2.6.0} -> 2.6.0 (c)
|    +--- com.google.errorprone:error_prone_type_annotations:2.6.0
+--- com.google.errorprone:error_prone_type_annotations:{strictly 2.6.0} -> 2.6.0 (c)
+--- com.google.errorprone:javac:9+181-r4173-1
\--- com.google.errorprone:javac:{strictly 9+181-r4173-1} -> 9+181-r4173-1 (c)
errorprone - Error Prone dependencies, will be extended by all source sets' annotationProcessor configurations
errorproneJavac - Error Prone Javac dependencies, will only be used when using JDK 8 (i.e. not JDK 9 or superior)
+--- com.uber.nullaway:nullaway:0.8.+ -> 0.8.0
+--- com.uber.nullaway:nullaway:{strictly 0.8.0} -> 0.8.0 (c)

------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.10 (AdoptOpenJDK 11.0.10+9)
OS:           Linux 5.11.10-200.fc33.x86_64 amd64
```

**Comment by msridhar** [comment]
@xenoterracide if NullAway treated `@MonotonicNonNull` as just an alias for `@Nullable` I think that would fix this case.  The only problem is that NullAway would not enforce the condition (checked by Checker Framework) that `@MonotonicNonNull` fields may only be assigned non-null values.  I don't think that is a soundness issue.  We'd of course need to document this behavior.  Can you think of any problems with this approach?

**Comment by xenoterracide** [comment]
currently, no, not really. I didn't just suggest that because it feels like maybe adding too much of a dependency on a 3rd party framework, but maybe that's acceptable in the case of checker. The only other approach I can think of is a custom annotation that other frameworks shouldn't use (thanks Oracle), which hints to Nullaway that it should treat as `@Nullable`.  Simply being `@Nullable` wouldn't work as most frameworks will use that by name. To be honest this is a general problem. I'm not even certain your approach is the right one. Maybe this needs to be fixed on the checker side, such that defining both won't break logic there...

**Comment by xenoterracide** [comment]
ok, I opened an issue there, my current reflection is that this is actually something they need to do, it just needs to be documented (implemented? for all I know this already works).

**Comment by xenoterracide** [comment]
btw, should I open another issue about the error? because that error really should tell you which field is causing the problem instead of just pointing to the constructor.

**Comment by msridhar** [comment]
>  I didn't just suggest that because it feels like maybe adding too much of a dependency on a 3rd party framework, but maybe that's acceptable in the case of checker.

We can just depend on the string name of the annotation without adding an actual classpath dep, so that should be ok.  This should be an easy fix, so we can look into it.

> btw, should I open another issue about the error? because that error really should tell you which field is causing the problem instead of just pointing to the constructor.

So the error location is the constructor, but the error message mentions the field and its location ("does not guarantee @NonNull field destination (line 72)").  We pick the constructor as the error location since (1) there could be multiple uninitialized fields and (2) there could be multiple constructors missing initialization of the field, and we want to report one error for each constructor.  Let us know if you think we could format the error message more clearly to make the issue more obvious.

**Comment by lazaroclapp** [comment]
We do have some special treatment of `@MonotonicNonNull` [here](https://github.com/uber/NullAway/blob/master/nullaway/src/main/java/com/uber/nullaway/ErrorProneCLIFlagsConfig.java#L121). Namely, we treat fields annotated with it as [excluded](https://github.com/uber/NullAway/wiki/Configuration#excluded-field-annotations) from proper initialization checking. 

The idea being to treat it as `@NonNull` so `= null` is invalid, but at the same time not check initialization. This is obviously unsound, since you can dereference it before any non-null assignment, getting an NPE, but it was considered a practical trade-off given how `@MonotonicNonNull` is used in practice (late initialization).

Given that, though, the fact that NullAway is throwing an initialization error on it looks like a proper bug to me.

Just to be sure, the annotations FQN is `org.checkerframework.checker.nullness.qual.MonotonicNonNull`, correct? That hasn't changed somehow? 

If so, this is weird, we even have a [test case](https://github.com/uber/NullAway/blob/f292bed2ec1c77f073c60af3445d19fc487f6918/nullaway/src/test/resources/com/uber/nullaway/testdata/CheckFieldInitNegativeCases.java#L325) for this behavior already.

**Comment by xenoterracide** [comment]
> Just to be sure, the annotations FQN is org.checkerframework.checker.nullness.qual.MonotonicNonNull, correct? That hasn't changed somehow?

updated the original post to include the entire file imports and all

> So the error location is the constructor, but the error message mentions the field and its location ("does not guarantee @nonnull field destination (line 72)"). We pick the constructor as the error location since (1) there could be multiple uninitialized fields and (2) there could be multiple constructors missing initialization of the field, and we want to report one error for each constructor. Let us know if you think we could format the error message more clearly to make the issue more obvious.

I think it'd be better to additionally give the field(s) name(s). Just my 2 cents. @mernst seems to agree with your proposal, also noting that

> @MonotonicNonNull is a subtype of @Nullable.

or rather you could inspect it to get there...

however none of that seems relevant based on the rest of the discussion here now.

**Comment by xenoterracide** [comment]
it is possible, depending on when that code changed this doesn't exist in the latest (added resolved versions above too) but due to https://github.com/uber/NullAway/issues/462 I haven't been able to test that.

**Comment by xenoterracide** [comment]
closing, after removing checkerframework so I could use the latest version this does not appear to exist
