### ISSUE TITLE
Objects.requireNonNull(value, Supplier<String>) is not recognized as a null check

### ISSUE THREAD

**Issue by dododge** [uber/NullAway#479]
Using NullAway 0.9.1.

This is similar to issue #276. The fix for that handled `requireNonNull()` with a `String` message, but there's another standard form of the method that takes a `Supplier<String>` that is not recognized.

```java
package example;

import java.util.Objects;
import org.jetbrains.annotations.Nullable;

public class Example
{
    public static String example(@Nullable String val) {
        Objects.requireNonNull(val, () -> "val is null");
        return val.trim();
    }
}
```

```
[WARNING] /path/to/example/Example.java:[10,18] [NullAway] dereferenced expression val is @Nullable
```

**Comment by msridhar** [comment]
@dododge any interest in submitting a PR?  It should be a simple fix, just adding an appropriate line around here (and a test):

https://github.com/uber/NullAway/blob/5d4b086ea0e68b6212fa24cfd69bf53d2ee4ff0d/nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java#L352-L353
