### ISSUE TITLE
Inconsistent behaviour between StringUtils.isBlank and identical method in our own code

### ISSUE THREAD

**Issue by hakanai** [uber/NullAway#488]
We're using v0.9.1.

As part of a greater effort to stomp out Commons Lang in our codebase, we had implemented a replacement for `StringUtils.isBlank`:

```java
public class BadStringUtils {
    @Deprecated
    public static boolean isBlank(@Nullable CharSequence string) {
        if (string == null) {
            return true;
        }

        int length = string.length();
        if (length == 0) {
            return true;
        }

        for (int i = 0; i < length; i++) {
            if (!Character.isWhitespace(string.charAt(i))) {
                return false;
            }
        }

        return true;
    }
```

The next step was to go through the code and replace all usage of Commons Lang3's StringUtils.isBlank with ours.

So we had this one:

```java
public class Guid {
    // ...

    @Nullable
    public static Guid parseOrNull(@Nullable String value) {
        if (!StringUtils.isBlank(value) && (value.length() == 36 || value.length() == 32)) {
            try {
                return fromString(value);
            } catch (IllegalArgumentException e) {
                // value wasn't a guid, fall through
            }
        }
        return null;
    }
}
```

And I just changed it to this:

```java
public class Guid {
    // ...

    @Nullable
    public static Guid parseOrNull(@Nullable String value) {
        if (!BadStringUtils.isBlank(value) && (value.length() == 36 || value.length() == 32)) {
            try {
                return fromString(value);
            } catch (IllegalArgumentException e) {
                // value wasn't a guid, fall through
            }
        }
        return null;
    }
}
```

And suddenly the NullAway check fails, even though as far as I can tell, the semantics have not.

I looked at `StringUtils.isBlank` to see whether it had annotations or something documenting the behaviour if `null` was passed in but I didn't see anything, so I feel like I just stepped on a land-mine.

Whatever is going on with `StringUtils.isBlank`, is there perhaps a way to annotate our method to get the same treatment?

**Comment by msridhar** [comment]
Thanks for the report!  I agree this is a bit confusing.  We wrote a built-in library model for `StringUtils.isBlank` indicating that when the argument is `null` the result will be `true`:

https://github.com/uber/NullAway/blob/bf11c2045b82bb96c4f8fe7cc7f007e1a2f95a64/nullaway/src/main/java/com/uber/nullaway/handlers/LibraryModelsHandler.java#L498-L502

You can write an annotation `@Contract("null -> true")` on `BadStringUtils.isBlank` to get the same effect.  Docs here:

https://github.com/uber/NullAway/wiki/Supported-Annotations#contracts

Does that solve the problem for you?

**Comment by hakanai** [comment]
Looks like this will work for us.

I had hoped that NullAway was looking inside `StringUtils.isEmpty` to see the null return behaviour, so it was surprising when the same code didn't work when it was just living in a different package, but I guess that wasn't the case.

**Comment by msridhar** [comment]
Yeah part of the reason NullAway is relatively fast is that it (mostly) doesn't do analysis across procedure boundaries.

Will close this out but please re-open if things don't work.
