### ISSUE TITLE
Mention @CheckForNull in Supported-Annotations wiki page

### ISSUE THREAD

**Issue by cpovirk** [uber/NullAway#506]
I noticed that https://github.com/uber/NullAway/wiki/Supported-Annotations doesn't mention `@CheckForNull`, which has been supported since #397. I'm not sure if there a good way to send a PR for the wiki, so I'm filing this issue instead :)

(This is potentially more important for us at Google now that we've [temporarily adopted `@CheckForNull` in Guava](https://github.com/google/guava/releases/tag/v31.0).)

**Comment by msridhar** [comment]
Thanks @cpovirk, I updated the docs!
