### ISSUE TITLE
NullAway does not recognize null-check methods properly

### ISSUE THREAD

**Issue by bejibx** [uber/NullAway#51]
Code example:
```java
public class Example {
    @Nullable
    private String text;

    @NonNull
    public String getText() {
        // NullAway raises error here
        return StringUtils.isEmptyOrNull(text) ? "Hello World!" : text;
    }
}

// isEmptyOrNull method
public static boolean isEmptyOrNull(@Nullable final CharSequence value) {
    return value == null || value.length() == 0;
}
```

Error message says
```
Error:(50, 13) error: [NullAway] returning @Nullable expression from method with @NonNull return type
(see http://t.uber.com/nullaway )
```

Error is gone when I inline ```isEmptyOrNull``` method call.

NullAway version is 0.1.7.

**Comment by msridhar** [comment]
NullAway is not able to reason across procedure calls to prove the original example safe.  Doing so could slow the tool down considerably.  That said, is this a well-known `StringUtils` class from a standard library?  If so we could maybe add a library model to catch this case.

**Comment by bejibx** [comment]
No, this is my own utility class. Actually, I used [TextUtils#isEmpty(CharSequence)](https://developer.android.com/reference/android/text/TextUtils.html#isEmpty(java.lang.CharSequence)) initially, but migrate to my own method because IntelliJ IDEA code inspections running on CI server were not able to analyze these situations properly. If NullAway is ok with android method I can potentially migrate back (which I don't want to do, because it is a LOT of code), but there are many other places in app, where similar null-checking logic involved. I also don't like to supress those warnings because I have to supress whole method, which is ok for above example, but may be unacceptable for larger methods. Maybe add an option to supress warning using comments similar to how Lint inspections being supressed?
```java
//noinspection Unchecked
return StringUtils.isEmptyOrNull(text) ? "Hello World!" : text;
```

**Comment by msridhar** [comment]
I think a good option here would be for you to add your own library model actually.  The process is documented [here](https://github.com/uber/NullAway/wiki/Configuration#library-models), but the docs are a bit sparse.  We should add a sample library model to show how it's done.  We'll work on that, but if you figure it out in the meantime let us know.

**Comment by bejibx** [comment]
> In addition to these options, NullAway will look for any classes implementing the com.uber.nullaway.LibraryModels interface...

It seems I have to use ```compile``` dependency instead of ```annotationProcessor``` to do so, which will add a lot of uneccessary dependencies (including huge Guava library) to my project, which I want to avoid.

**Comment by msridhar** [comment]
@bejibx I just added a sample library model on master; see #53.  It's used by the sample app just by adding an annotation processor dependency; no need to pollute your app's classpath.  Does this look like a reasonable solution?

**Comment by msridhar** [comment]
btw for targeted suppressions, you can "downcast" any particular expression from `@Nullable` to `@NonNull` with a `castToNonNull` utility method; see [here](https://github.com/uber/NullAway/wiki/Suppressing-Warnings#downcasting)

**Comment by msridhar** [comment]
Gonna close this out as I think it's solved; @bejibx please let us know if you need further help

**Comment by bejibx** [comment]
Sorry for late response, yeah, I managed to fix those errors by implementing ```LibraryModels``` in separate module.
