### ISSUE TITLE
Allow local builds via publichToMavenLocal task with -LOCAL postfix

### ISSUE THREAD

**Issue by nimakarimipour** [uber/NullAway#515]
```NullAway``` version at the time reporting this issue: ```0.9.3-SNAPSHOT```

In ```gradle.propertis``` file, if the value of ```VERSION_NAME``` for local builds is set to ```x.x.x-LOCAL``` where ```x.x.x``` is version number, ```publishMavenLocal``` fails with the following error:
```
Execution failed for task ':nullaway:signMavenPublication'.
> Cannot perform signing task ':nullaway:signMavenPublication' because it has no configured signatory
```

Below is the output of running ```./gradlew publishToMavenLocal --dry-run```
```
.
.
.
:nullaway:sourcesJar SKIPPED
:nullaway:signMavenPublication SKIPPED
:nullaway:publishMavenPublicationToMavenLocal SKIPPED
:nullaway:publishToMavenLocal SKIPPED
...
```

If we use the original format for ```VERSION_NAME``` and use ```x.x.x-SNAPSHOT```, ```:nullaway:signMavenPublication``` is no longer in the set of tasks and we can successfully install to ```maven local```.

With best regards

**Comment by msridhar** [comment]
@nimakarimipour based on [the docs](https://github.com/vanniktech/gradle-maven-publish-plugin#signing) for the publishing plugin, I think you can disable signing manually with the following command:
```
./gradlew -PRELEASE_SIGNING_ENABLED=false publishToMavenLocal
```
Signing is disabled by default only for `SNAPSHOT` versions.  Can you try and see if it works with a `LOCAL` version?

**Comment by msridhar** [comment]
@nimakarimipour closing under the assumption that the above works.  If it doesn't work for you please reopen
