### ISSUE TITLE
Possible bug in Optional.empty() check with exception handling

### ISSUE THREAD

**Issue by noobgramming** [uber/NullAway#557]
Hello! I'm trying out `CheckOptionalEmptiness` and I think I found a bug.

It reports Optional after exception handling as possibly empty, even if all code paths in try{} throw or return. And it does so even when you pre-initialize to Optional.empty()

**This code example isn't right, see updated one a few comments below**
```java
    Optional<Object> optObject = Optional.empty(); //<-- thought initializing to empty would fix lint, it doesn't
    try {
      optObject = doAThingThatMightThrow(optObject); // <-- the object this returns isn't nullable either
    } catch (Exception e) {
      if (configuration.debugMode()) {
        throw e; // <-- this path always throws
      } else {
        log.error(
            "Not debug mode, logging error and continuing on",
            e);
        return new ResponseObject(); <-- and the other path here always returns
      }
    }
    if (optCommand.isEmpty()) {
       // do stuff
    } else {
      final var object = optObject.get(); // <-- lint reports error here [NullAway] Invoking get() on possibly empty Optional optObject
```

**Comment by msridhar** [comment]
Hi @noobgramming, for this line:
```java
if (optCommand.isEmpty()) {
```
Should that be `optObject` rather than `optCommand`?  I don't see `optCommand` declared anywhere.

**Comment by lazaroclapp** [comment]
Hey @msridhar, waiting for confirmation from @noobgramming , but I think the if check is indeed on an unrelated variable, and the logic for why `optObject` is non-empty can be simplified to:

```
Optional<Object> optObject = Optional.empty();
try {
  o = doAThingThatMightThrow(optObject);
} catch(Exception e) {
  return; // Unconditional return
}
final var object = o.get();
```

In that case, I do see a discrepancy between our handling of `null` and our handling of `empty()`.

See the following test cases:

```
  @Test
  public void testTrySanity() {
    makeTestHelperWithArgs(
            Arrays.asList(
                    "-d",
                    temporaryFolder.getRoot().getAbsolutePath(),
                    "-XepOpt:NullAway:AnnotatedPackages=com.uber",
                    "-XepOpt:NullAway:UnannotatedSubPackages=com.uber.lib.unannotated",
                    "-XepOpt:NullAway:CheckOptionalEmptiness=true"))
            .addSourceLines(
                    "Test.java",
                    "package com.uber;",
                    "import java.util.Optional;",
                    "class Test {",
                    "   Object test(){",
                    "     Optional<Object> o = Optional.empty();",
                    "     try {",
                    "       o = Optional.of(\"something\");",
                    "     } catch (Exception e) {",
                    "       return \"error\";",
                    "     }",
                    // Unexpected error here: [NullAway] Invoking get() on possibly empty Optional o
                    "     return o.get();",
                    "   }",
                    "}")
            .doTest();
  }

  // Passes, as expected.
  @Test
  public void testTrySanity2() {
    defaultCompilationHelper
            .addSourceLines(
                    "Test.java",
                    "package com.uber;",
                    "import javax.annotation.Nullable;",
                    "class Test {",
                    "   Object test(){",
                    "     Object o = null;",
                    "     try {",
                    "       o = \"something\";",
                    "     } catch (Exception e) {",
                    "       return \"error\";",
                    "     }",
                    "     return o;",
                    "   }",
                    "}")
            .doTest();
  }
```

**Comment by msridhar** [comment]
@lazaroclapp that's really interesting.  I have no idea why there is an error reported for the `Optional` version of your test.  It will take some digging into the dataflow analysis to figure it out.  This is a nice catch!

**Comment by noobgramming** [comment]
> Hi @noobgramming, for this line:
> 
> ```java
> if (optCommand.isEmpty()) {
> ```
> 
> Should that be `optObject` rather than `optCommand`? I don't see `optCommand` declared anywhere.

Yes sorry. This was extracted from much larger, more confusing code :) I tried to simplify

**Comment by msridhar** [comment]
Thanks, @noobgramming.  This definitely looks like a bug.  We will look as soon as we get some time

**Comment by msridhar** [comment]
I finally got some time to dig a bit into this.  I found that the same kind of false positive occurs with this test:
```java
  @Test
  public void returnFromCatch() {
    defaultCompilationHelper
        .addSourceLines(
            "Test.java",
            "package com.uber;",
            "import javax.annotation.Nullable;",
            "class Test {",
            "  @Nullable Object f;",
            "  String foo() {",
            "    Test t = new Test();",
            "    try {",
            "      t.f = new Object();",
            "    } catch (Exception e) {",
            "      return \"error\";",
            "    }",
                 // false positive warning for this line
            "    return t.f.toString();",
            "  }",
            "}")
        .doTest();
  }
```
The issue turns out to have nothing to do with exceptions.  The issue is that we will not track an access path for a field if the root is not `this`:
https://github.com/uber/NullAway/blob/f3c1ebfc20e06249369115e8be12aac66cb77ea4/nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessPropagation.java#L531-L540

I presume we did this for performance reasons way back when (this code has not changed since the initial open-source commit of NullAway).  This impacts handling of the optional case as well, since we simulate the contents of an `Optional` object as a pseudo-field.

The downside of this optimization is confusing tool behavior, like in the case originally reported here.  I'd be open to trying to track more access paths as part of analysis, as long as we measure the performance impact, both on our micro-benchmarks and also on internal code at Uber.  E.g., we could track an access path after an assignment to a field of any local variable, not just `this`.  I would not expect too much of a blowup from that.

@lazaroclapp any thoughts here?  I may hold off on this change until after the next release, since at that point we expect to add NullAway itself as another performance benchmark.

**Comment by msridhar** [comment]
🤦‍♂️ Ignore my previous comment.  I figured out something much simpler is going on here; we don't have any support for the `Optional.isEmpty()` method!  It was added in Java 11 but our handler doesn't know about it.  This should be much easiesr to fix 🙂
