### ISSUE TITLE
can you supply a android demo?

### ISSUE THREAD

**Issue by wzyzb** [uber/NullAway#59]
i can not config build.gradle.

**Comment by msridhar** [comment]
Hi @wzyzb, sure, we can set up an Android demo project.  The Android config is documented [here](https://github.com/uber/NullAway#android), and it's pretty similar to the [vanilla Java config](https://github.com/uber/NullAway#java-non-android).  Can you let us know what isn't working for you?

**Comment by kaoxiang** [comment]
I have the same problem......... after I change my build.gradle files in top level and model level      
the console shows: An unhandled exception was thrown by the Error Prone static analysis plugin.

**Comment by msridhar** [comment]
@wzyzb @kaoxiang I added a sample Android app now.  It uses Gradle plugin 3 but I confirmed that everything works the same with Gradle plugin 2.3.  I have *not* tested with Gradle 3.3.  I recommend upgrading Gradle, but if you need to stay on the older version and find things don't work, please open another issue.
