### ISSUE TITLE
Investigate and resolve performance regression from #639

### ISSUE THREAD

**Issue by lazaroclapp** [uber/NullAway#645]
Context: https://github.com/uber/NullAway/pull/641#issuecomment-1232134787 and previous comments in #641

**Comment by msridhar** [comment]
I collected profiles again and nothing definitive jumps out beyond what I saw before.  I think the most promising path for getting rid of the remaining regression is switching to `Nullness[]`: https://github.com/uber/NullAway/pull/646#discussion_r959788282
