### ISSUE TITLE
Try switching to vanilla Checker Framework Dataflow 2.2.2

### ISSUE THREAD

**Issue by msridhar** [uber/NullAway#65]
[Error Prone](https://github.com/google/error-prone/pull/847) has updated to this version.  We were blocked on typetools/checker-framework#1504, but I think typetools/checker-framework#1589 may have fixed that problem.

**Comment by msridhar** [comment]
Looks like Error Prone [backed out their update](https://github.com/google/error-prone/commit/50a78bdd7feb56de69835acd741b775f9d32e7a1).  We don't need to be in a hurry on this one.

**Comment by chengniansun** [comment]
Ah, I updated error-prone to this version, and rolled back. The motivation for the update is NullAway, and now this looks very interesting.

**Comment by msridhar** [comment]
@chengniansun NullAway uses its own shaded version of the checker framework dataflow library, so it shouldn't interfere at all with the version used by Error Prone.  If you notice any interference please let us know.

**Comment by msridhar** [comment]
Closing this; we're going to shadow to avoid compatibility issues for the foreseeable future, and we have already bumped our CF dependence
