### ISSUE TITLE
Getting following error : > Could not find method errorprone() for arguments [com.google.errorprone:error_prone_core:2.15.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

### ISSUE THREAD

**Issue by prasanjeit** [uber/NullAway#664]
Thanks for using NullAway. Before you create an issue, please consider the following points:

  - [ ] If you think you found a bug, please include a code sample that reproduces the problem. A test case that reproduces the issue is preferred. A stack trace alone is ok but may not contain enough context for us to address the issue.

  - [ ] Please include the library version number, including the minor and patch version, in the issue text.

On adding the dependencies mentioned we are getting following error "> Could not find method errorprone() for arguments [com.google.errorprone:error_prone_core:2.15.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler."

Have tried with multiple versions but no result.

Sample code in dependencies.gradle

    //NullAway
    annotationProcessor "com.uber.nullaway:nullaway:0.10.1"
    errorprone "com.google.errorprone:error_prone_core:2.0.4"
    errorproneJavac "com.google.errorprone:javac:9+181-r4173-1"

**Comment by msridhar** [comment]
The Gradle ErrorProne plugin provides the `errorprone` configuration:

https://github.com/tbroyer/gradle-errorprone-plugin

Can you double-check you have configured that plugin correctly, and that other Error Prone checks can run?

**Comment by prasanjeit** [comment]
Hi @msridhar ,

Checked the configuration as mentioned still receiving the same error:
"> Could not find method errorprone() for arguments [build_3*********$_run_closure7$_closure4****] on task ':compileJava' property 'options' of type org.gradle.api.tasks.compile.CompileOptions."

**Comment by msridhar** [comment]
Hard to help just with the info you provided. If you can make a GitHub sample repo that fails in the same way I can try to help.

**Comment by msridhar** [comment]
This is most likely not an error related to NullAway so closing for now
