### ISSUE TITLE
Support com.google.common.base.Verify.verifyNotNull and com.google.common.base.Verify.verify​

### ISSUE THREAD

**Issue by toellrich** [uber/NullAway#666]
It would be great if NullAway could support Guava's [Verify](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/base/Verify.html) class analogous to its [Preconditions ](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/base/Preconditions.html)class.

**Comment by msridhar** [comment]
Thanks for the report @toellrich.  Do you specifically mean the `verifyNotNull()` methods in that class, or something else?  If it's just `verifyNotNull()` that should be fairly easy to support.

**Comment by toellrich** [comment]
My thinking was that `verifyNotNull()`  should be analogous to `checkNotNull` and that `verify` should be analogous to `checkArgument` or am I mistaken?

**Comment by msridhar** [comment]
Yes I think you're right.  We'll try to add support here; it shouldn't be too hard.

**Comment by msridhar** [comment]
The fix for this issue is part of the just-released NullAway 0.10.3
