### ISSUE TITLE
Nullness checks on final fields should be preserved through stream handling

### ISSUE THREAD

**Issue by lazaroclapp** [uber/NullAway#699]
Consider:

```
public final class Foo {
   @Nullable private final Object o;

   private String bar(Stream<String> stream) {
     Preconditions.checkNotNull(o);
     return stream.filter(s -> o.toString().equals(s)).getAny();
   }
}
```

This will result in an error reported at `o.toString()`, claiming `o` can be `@Nullable`. This makes sense for a non-`final` field, since there is no guarantee other methods won't execute between the check in `Foo.bar` and the execution of the lambda. However, if we know `o` is `final`, then it's sufficient to know that the lambda will execute _after_ the preconditions check, without worrying about how long after. 

Currently, the only solution here is to either move the check to be inside the lambda, or copy the field to a `@NonNull` final local:

```
public final class Foo {
   @Nullable private final Object o;

   private String bar(Stream<String> stream) {
     Preconditions.checkNotNull(o);
     final Object o2 = o;
     return stream.filter(s -> o2.toString().equals(s)).getAny();
   }
}
```

This is a related issue to #697, but much easier, since it involves no mutability, not even deep mutability as in the map case noted there.

**Comment by msridhar** [comment]
This _should_ be a fairly simple fix.  The relevant code is here:

https://github.com/uber/NullAway/blob/5ccffb539f54f30af1ae3f90602fcedaa3fd18a1/nullaway/src/main/java/com/uber/nullaway/dataflow/AccessPathNullnessAnalysis.java#L225-L237

We would just need to change the filter to also include access paths with zero elements rooted at a final field.
