### ISSUE TITLE
Does not compile with Parceler lib - @Parcel implementation annotation

### ISSUE THREAD

**Issue by tspoke** [uber/NullAway#72]
Hi,

I tried to use NullAway in a project with no success. My problem was related to the Parceler library.
- If I remove NullAway, my project compiles and works fine. 
- If I remove the `implementation =
 {MyClassRealmProxy.class}` in the `@Parcel` declaration on my model, the project compiles and NullAway works.

I tried to use this configuration with no success to ignore generated classes (<Class>$$Parcelable) :  
```
options.compilerArgs += [
            "-Xep:NullAway:ERROR",
            "-XepOpt:NullAway:AnnotatedPackages=com.test.nullaway",
            "-XepOpt:NullAway:ExcludedClassAnnotations=org.parceler.Generated"
]
```

## The error 

```
error: Parceler: Code generation did not complete successfully.
  org.parceler.transfuse.transaction.TransactionRuntimeException: Encountered ErrorType <error>, unable to recover
```

## How to reproduce ?

I made a project to demonstrate the problem. You can clone it and try to build it : [https://github.com/tspoke/nullaway-parceler](https://github.com/tspoke/nullaway-parceler)

This demo project use Parceler and Realm.

**Comment by msridhar** [comment]
Thanks for the report!  @lazaroclapp any chance you could take a quick look?

**Comment by msridhar** [comment]
I just tried this out, and it looks like this is an issue with Error Prone itself.  If I comment out all the NullAway stuff in `app/build.gradle` the build still fails; see https://github.com/msridhar/nullaway-parceler.  Looks like this is some incompatibility between Parceler and Error Prone.  I'd try reporting to either the Parceler or EP folks.

Gonna close this one for now, but if you think this is in fact a NullAway issue pls reopen.

**Comment by tspoke** [comment]
I opened an issue in the ErrorProne repository. Thank you for your time ;)

https://github.com/google/error-prone/issues/857
