### ISSUE TITLE
Recognize JUnit 5's @BeforeAll and @BeforeEach as initializers

### ISSUE THREAD

**Issue by michaelhixson** [uber/NullAway#73]
NullAway should recognize JUnit 5's `@BeforeAll` and `@BeforeEach` as initializer annotations by default.  Currently it recognizes JUnit 4's `@Before` and `@BeforeClass`, but in JUnit 5 these were renamed:

* [`org.junit.jupiter.api.BeforeAll`](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/BeforeAll.html)
* [`org.junit.jupiter.api.BeforeEach`](http://junit.org/junit5/docs/current/api/org/junit/jupiter/api/BeforeEach.html)

Since you provided the `CustomInitializerAnnotations` option, users can work around this by passing an argument to javac:

```
-XepOpt:NullAway:CustomInitializerAnnotations=org.junit.jupiter.api.BeforeAll,org.junit.jupiter.api.BeforeEach
```

...but I think it makes sense to support this by default so users don't have to do that.

Resolving this issue should be a matter of changing these lines:

https://github.com/uber/NullAway/blob/c48edad9c2280eb2941126b6b26c85edf1953485/nullaway/src/main/java/com/uber/nullaway/ErrorProneCLIFlagsConfig.java#L60-L63

to this:

```java
static final ImmutableSet<String> DEFAULT_INITIALIZER_ANNOT =
    ImmutableSet.of(
        "org.junit.Before",
        "org.junit.BeforeClass",
        "org.junit.jupiter.api.BeforeAll",
        "org.junit.jupiter.api.BeforeEach");
```

Adding test cases could be awkward since you'd need to bring in a JUnit 5 dependency probably?  Or you could not add tests.

**Comment by msridhar** [comment]
@michaelhixson looks like a good change.  Could you submit a PR with the change?  Tests not required.

**Comment by michaelhixson** [comment]
@msridhar I'm not comfortable with signing the CLA, so I closed the PR.  Sorry for the noise.  I still think the change is a good idea though.

**Comment by msridhar** [comment]
@michaelhixson can you contact me 1-1 (email on my website, linked from my profile)?  Wanted to follow up briefly on the CLA issues.  Thanks!
