### ISSUE TITLE
Private static variable initialized inside constructor

### ISSUE THREAD

**Issue by Asapin** [uber/NullAway#761]
I found an interesting case while integrating NullAway into a project: `private static` variable initialized inside constructor.
This variable is initialized inside the constructor and it can't be accessed from the outside of the class, it's accessed only from the inside of the class. So effectively it will always be initialized.

But NullAway shows an error that the variable is not initialized:
```text
[ERROR] /src/main/java/org/asynchttpclient/handler/resumable/ResumableAsyncHandler.java:[51,38] [NullAway] @NonNull static field resumableIndex not initialized
[ERROR]     (see http://t.uber.com/nullaway )
```

Class in question: https://github.com/AsyncHttpClient/async-http-client/blob/main/client/src/main/java/org/asynchttpclient/handler/resumable/ResumableAsyncHandler.java#L50 

Minimal reproducible example:
```java
public class ClassA {
    private static String testString;

    public ClassA(String parameter) {
        testString = parameter;
    }

    private void printString() {
        System.out.println(testString);
    }
}
```

**Comment by msridhar** [comment]
@Asapin I think NullAway requires initializing your `testString` field in a static initializer.  If you write `private static String testString = "";` then I believe it will pass NullAway.  Can you try it?

**Comment by msridhar** [comment]
BTW, even though you are correct that the code is safe as you wrote it, NullAway tries to prove safety using local reasoning, without analyzing the whole class, so it doesn't handle this case.

**Comment by Asapin** [comment]
Yes, it will work if I initialize it in a static block.
But the issue is that in the actual code static field is initialized with an existing `Map` instance to avoid unnecessary copies and allocations

**Comment by msridhar** [comment]
You could initialize to Collections.emptyMap() which won't allocate anything I think.

**Comment by msridhar** [comment]
I am going to go ahead and close this but if there is a further NullAway issue please reopen
