### ISSUE TITLE
Nullaway does not recognize @NullableDecl from the checker framework.

### ISSUE THREAD

**Issue by chengniansun** [uber/NullAway#82]
Recently, guava has moved from jsr 305 to the annotations of the checker framework. And it uses @NullableDecl extensively. Do you have any plan to support this? 

Thank you.

**Comment by JakeWharton** [comment]
#27

**Comment by msridhar** [comment]
Sure, we can support this.  I'll look into it.

**Comment by msridhar** [comment]
@JakeWharton just supporting `@NullableDecl` is probably a lot less work than fixing #27 (which would require integrating parsing of Checker Framework stub files, etc.).  Is there a strong need for fixing #27 as well?

**Comment by JakeWharton** [comment]
I assumed this would be a subset, as more an more of checker is supported.
I guess that issue is solely for their JDK stuff though.

**Comment by msridhar** [comment]
> I assumed this would be a subset, as more an more of checker is supported. I guess that issue is solely for their JDK stuff though.

Yup, this could kind of be viewed as a subset, assuming their JDK stuff is also using `@NullableDecl`.

**Comment by chengniansun** [comment]
Thanks, Manu.

**Comment by msridhar** [comment]
@chengniansun would it be helpful for us to cut a new release with this fix?

**Comment by chengniansun** [comment]
Thank you. I have no preference as I have switched to the SNAPSHOT this morning.
