### ISSUE TITLE
Create a snapshot version on mvn repository?

### ISSUE THREAD

**Issue by chengniansun** [uber/NullAway#88]
Do you plan to create a snapshot version on the maven repository? 

I believe that there must some way to setup building guava with the trunk of NullAway. However, I know nothing about maven, and it seems using the snapshot version is the easiest way. 

Thank you.

**Comment by msridhar** [comment]
We already have snapshot builds [on Sonatype](https://oss.sonatype.org/content/repositories/snapshots/com/uber/nullaway/).  Can you give those a try and let us know if something doesn't work?

**Comment by chengniansun** [comment]
Thank you, Manu. 

In order to enable the snapshot, I need to add the following in my pom.xml. However I did not find any way to edit the wiki, so pasted it here. 

    <repositories>
        <repository>
            <id>oss-sonatype</id>
            <name>oss-sonatype</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <updatePolicy>daily</updatePolicy>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
