### ISSUE TITLE
Figuring out nullability based on enum tag and publicly exposed constructors

### ISSUE THREAD

**Issue by dipeshkaphle** [uber/NullAway#890]
Consider the following class

```java

import lombok.Getter;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

@Getter
public class Result<T,E extends Exception>{
  @Nullable private final T value;
  @Nullable private final E exception ;
  @Nonnull private final Tag tag;


  private Result(@Nullable T val, @Nullable E e, @Nonnull Tag tag){
    this.tag = tag;
    this.value = val;
    this.exception = e;
  }

  public static <T> Result<T, ?> fromValue(@Nonnull T value){
    return new Result<>(  value, null, Tag.VALUE);
  }
  public static <E extends Exception> Result<?,E> fromException(@Nonnull E e){
    return new Result<>(null, e, Tag.EXN);
  }
}
```

```java
public enum Tag{
  VALUE,
  EXN
}

```

and consider it's usage is as follows:

```java

Result<String> result1=  Result.fromValue("Something");
if(Result.Tag.VALUE.equals(result1.getTag())){
  String value =  result1.getValue();
  int length = value.length();
  // do whatever here
}
```

The above code gets flagged by nullaway but we know for a fact that `getValue()` will never
return null since our publicly exposed constructors are designed that way. 
Nullaway should be able to figure this out ideally right? Figuring out this information 
is a matter of peeking into the constructor function and storing some information about how
it's constructed.

I believe it's safe to infer this as well if I'm not mistaken since our class is immutable. I
think this is a popular pattern as well, so supporting this would be quite nice.

Also for cases when the construction of `Result` happens in same scope as its usage, we could
also enable code like this without nullaway flagging us

```java
Result<String> result1=  Result.fromValue("Something");
// something happens
int length = result1.getValue().length();
// some more things happen
```

What do you guys think about this? Is this feasible? If it is, I would love to take this up

**Comment by msridhar** [comment]
Hi @dipeshkaphle thanks for the report.  NullAway performs modular, type-based checking.  I think the property you want to capture here is if the `tag` field of a `Result` object `r` is `VALUE`, then `r.getValue()` returns `@NonNull`.  Discovering this property automatically would require analyzing the entire `Result` class, which could be expensive, and in general we like to avoid such global analysis.  And, we do not have a way to capture this desired property using annotations.  I don't think it would be straightforward to add support for this case to NullAway; it would require some thought as to both design and implementation.  Also the fact that Lombok is being used here makes it even trickier, as the relevant getter methods do not appear in any source code.

A short-term fix would be to use a [downcast](https://github.com/uber/NullAway/wiki/Suppressing-Warnings#downcasting) around the relevant calls to `getValue()` or an explicit null check.  I realize that's kind of gross.  But, at this point, doing the kind of analysis required to automatically handle these examples is a bit out of scope for a tool like NullAway.  I'll think more and see if I can come up with a better solution.

**Comment by msridhar** [comment]
Here is an alternate way to write your code pattern, where instead of an explicit tag you use inheritance.

```java
abstract class /* or interface */ Result<T,E> {}
class ValueResult<T> extends Result<T,Void> {
  /* return is @NonNull */
  T getValue() { ... }
}
class ExceptionResult<E> extends Result<Void,E> {
  E getException() { ... }
}
...
void foo(Result<String> r) {
  if (r instanceof ValueResult) {
    String s = ((ValueResult)r).getValue(); 
  }
}
```
It's a rough sketch but hopefully you get the idea.  I would expect the `instanceof` checks to be potentially more efficient than the tag checks (you'd save space by getting rid of one field in the object).  And NullAway can easily reason about it.

Would the above coding pattern work for you @dipeshkaphle?  If not I'm curious why.

**Comment by dipeshkaphle** [comment]
With that, I'll close this too

**Comment by msridhar** [comment]
Note that the code pattern becomes even cleaner in Java 21 with sealed interfaces and pattern matching.  See here, which is an example very similar to yours:

https://softwaremill.com/java-21-switch-the-power-on/#unleash-the-power-of-switch-and-pattern-matching
