### ISSUE TITLE
Wiki Jakarta Annotations API

### ISSUE THREAD

**Issue by xenoterracide** [uber/NullAway#908]
So I just found out that v2 supports Nullable/Nonnull Although I don't think you should mention *every* annotation library ever... I think mentioning this is worth it, since it's the spiritual successor to findbugs jsr305 (I'd argue) and maybe someone else would learn about it this way.

**Comment by msridhar** [comment]
Where do you think this should be better documented?  On the Supported Annotations page we have this, indicating that any `@Nullable` annotation is supported:

https://github.com/uber/NullAway/wiki/Supported-Annotations#nullability

Is that what you're looking for?

**Comment by xenoterracide** [comment]
yeah, I was just thinking it would be worth specifically mentioning jakarta, since it's basically a light copy over from javax.annotation. Although it seems everyone? is going to go to jspecify... or something, it's not clear to me what that's actually going to mean.
