### ISSUE TITLE
Support for `collect()` in Streams API

### ISSUE THREAD

**Issue by jdcaperon** [uber/NullAway#933]
How hard would it be to support nullability within stream reducers such as `collect()`?

https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html#collect-java.util.stream.Collector-

```
class Scratch {
  public class Foo {
    @Nullable
    private final String bar;
    private final String baz;
    public Person(String bar, String baz) {
      this.bar = bar;
      this.baz = baz;
    }
  }

  void streams() {
    List<Person> foos = new ArrayList<>();
    foos.stream()
        .filter(f -> f.bar != null)
        // NullAway complains about nullability of name even though name is enforced
        .collect(Collectors.toMap(f -> f.bar, f -> f.baz));
  }
}
```

I had a look at how I might support this in the existing model but I think this would require supporting a new kind of method class (reductions) on streaming models. Understandably this might be a bit hard...

**Comment by jdcaperon** [comment]
Hi @msridhar, I actually missed a key detail of this, it may not be related to streams at all!

```
class Scratch {
  public record Foo(@Nullable String bar, String baz){}
  record Qux(String a, String b){}
  record Transformer(){
    public static Qux transform(String bar) {
      var split = bar.split("-");
      return new Qux(split[0], split[1]);
    }
  }
  void streams() {
    List<Foo> foos = List.of(new Foo("a-b", "c"));
    foos.stream()
            .filter(f -> f.bar != null)
            // NullAway complains about nullability of bar even though bar is null checked
            .collect(Collectors.toMap(f -> Transformer.transform(f.bar), f -> f.baz));
  }
}
```

https://github.com/jdcaperon/nullaway-java-sample/pull/1/files

I have created a repro here. This might be an issue with lambda's and such. Using an intermediate `.map()` makes the collector happy by removing the function call inside.

```
server/Scratch.java:24: error: [NullAway] passing @Nullable parameter 'f.bar' where @NonNull is required
        .collect(Collectors.toMap(f -> Transformer.transform(f.bar), f -> f.baz));
```

> settings

Version: 0.10.24
Installed via Bazel Plugin

**Comment by jdcaperon** [comment]
Hi @msridhar, I am not able to reproduce the issue in your environment, however I did miss a detail about a function call within a collect lambda that might be the root cause instead. I have created a repro here. This might be an issue with lambda's and such instead.

https://github.com/jdcaperon/nullaway-java-sample/pull/1/files

As for the original issue, which is still failing in my environment.

```
server/Scratch.java:24: error: [NullAway] passing @Nullable parameter 'f.bar' where @NonNull is required
        .collect(Collectors.toMap(f -> Transformer.transform(f.bar), f -> f.baz));
```

> settings

Let me get back to you on this I might be able to repro in your env with our settings.

```
Version: 0.10.24

Do you want all ErrorProne settings or just the NullAway ones?

```
common --javacopt="-Xep:NullAway:ERROR"
common --javacopt="-XepOpt:NullAway:AnnotatedPackages=com.canva"
common --javacopt="-XepOpt:NullAway:ErrorURL=..."
common --javacopt="-XepOpt:NullAway:ExternalInitAnnotations=com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable"
common --javacopt="-XepOpt:NullAway:ExcludedClassAnnotations=javax.annotation.processing.Generated"
```

Given it's not reproducable on the default I can try changing settings until it works on my end 👍

**Comment by jdcaperon** [comment]
@msridhar I think this is a confusion on my end. I thought I had an example but apparently not. I think this may be an extension of: https://github.com/uber/NullAway/issues/332

I'm going to close this ticket to avoid confusion, but I can re-raise it with the specific example of streams failure if needed.

**Comment by msridhar** [comment]
Ok, thanks, @jdcaperon!  Please report back if you have other use cases, and we can look into them.
