### ISSUE TITLE
Extract methods in StreamNullabilityPropagator

### ISSUE THREAD

**Issue by msridhar** [uber/NullAway#944]
Not for this PR, but wonder if as a follow up you want to extract the other two cases of this if into their own methods too, with `onMatchMethodInvocation(...)` as just a dispatcher.

_Originally posted by @lazaroclapp in https://github.com/uber/NullAway/pull/938#discussion_r1536699651_

**Comment by etrandafir93** [comment]
hello @msridhar, if this is still needed - I have created a [small PR](https://github.com/uber/NullAway/pull/985) and applied the changes suggested in the initial review.

If you have time to take a look, let me know what you think!
Cheers, Emanuel
