### ISSUE TITLE
Support annotation of guard methods

### ISSUE THREAD

**Issue by ben-manes** [uber/NullAway#96]
When adding NullAway, I receive a false positive. The failing branch is only executed if the non-null and this check is delegated to another method.

```
error: [NullAway] dereferenced expression future is @Nullable
    return isReady(future) ? future.join() : null;
```

```java
/** Returns if the future has successfully completed. */
static boolean isReady(@Nullable CompletableFuture<?> future) {
  return (future != null) && future.isDone()
      && !future.isCompletedExceptionally()
      && (future.join() != null);
}

/** Returns the current value or null if either not done or failed. */
static @Nullable <V> V getIfReady(@Nullable CompletableFuture<V> future) {
  return isReady(future) ? future.join() : null;
}
```

**Comment by msridhar** [comment]
NullAway does not reason across procedure boundaries about nullness checks, so it won't be able to prove this safe.  If you frequently use the `getIfReady` method to check for nullness, you can handle this with a [custom library model](https://github.com/uber/NullAway/wiki/Configuration#library-models); see #51 

Closing, but please re-open if you have more questions

**Comment by msridhar** [comment]
Re-opening as we should support this case with an annotation.  The user should be able to write something like:
```java
@RetTrueImpliesNonNullParam(0)
static boolean isReady(@Nullable CompletableFuture<?> future) {
  return (future != null) && future.isDone()
      && !future.isCompletedExceptionally()
      && (future.join() != null);
}
```
The annotation means that if the function returns true, the 0th parameter `future` cannot be null.  We also want `@RetFalseImpliesNonNullParam` or the like (naming TBD).  We could trust the annotations at first but maybe eventually check them.

**Comment by ben-manes** [comment]
Maybe something like `@ImpliesNonNullParam(when = true, param = 0)`

**Comment by ben-manes** [comment]
Actually, for an Iterator I think it should be `params` should with an array of strings. For example, I'd like to assert that `key` and `value` are non-null id `hasNext()` is true.

```
public Entry<K, V> next() {
  if (!hasNext()) {
    throw new NoSuchElementException();
  }
  Entry<K, V> entry = new WriteThroughEntry<>(cache, key, value);
  removalKey = key;
  value = null;
  next = null;
  key = null;
  return entry;
}
```

**Comment by msridhar** [comment]
I think the `hasNext` example is about non-nullness of fields of the receiver object, yes?  We could support that too, though it'd take a bit more work.

**Comment by ben-manes** [comment]
Yep, they are different cases of a similar problem. Thanks!

**Comment by lazaroclapp** [comment]
Ok, so, @msridhar, question: Are we currently shipping any support library for `NullAway` where we could put this new custom annotation? If not, I think we should, together with the `castToNonNull` method. As for `@ImpliesNonNull`, I think it can take either an array of arguments or an array of access paths. The later case would probably come at a performance cost, but we can make sure we only pay it when people use this annotation. We can talk more about this 1:1.

**Comment by hzsweers** [comment]
Similarly - supporting jetbrains' `@Contract` annotations could help here

**Comment by ben-manes** [comment]
Thanks you!

**Comment by msridhar** [comment]
To be clear, we don't yet support cases involving fields like the one @ben-manes outlined [here](https://github.com/uber/NullAway/issues/96#issuecomment-354638317).  I'll open a follow-up task on that.
