### ISSUE TITLE
Maven NullAway setup not detecting anything in the project

### ISSUE THREAD

**Issue by Wolf2323** [uber/NullAway#979]
I am completely new to nullaway, so may this is only a bad configuration or misunderstanding of the setup but when i run my maven project with `mvn verify` no errors are detected in the project (I am sure there are some) even if i copy the failing example code from the readme in my code.

maven-compiler-plugin: 3.10.1
error_prone_core: 2.27.1
nullaway: 0.10.26

The complete setup I added can be seen in this PR, I already opened in my project: https://github.com/BetonQuest/BetonQuest/pull/2812/files

**Comment by msridhar** [comment]
Looks like you're running into https://github.com/google/error-prone/pull/4162.  Can you try bumping the maven-compiler-plugin version to at least 3.11.0?  Alternately you can pass `-Xep:NullAway:ERROR` I think and you should see errors.

Please let us know if that fixes things.

**Comment by Wolf2323** [comment]
Yes, updating maven-compiler-plugin solved my problem. Thank you for the fast and helpful response!
